"""Durable M4 orchestration: embed an active chunk dataset, stage it, verify it, then activate.

The shape mirrors M2 and M3 — a fenced lease, the transactional outbox, one atomic commit of
durable state — with one addition that matters: the vector index is a second system that offers no
cross-store transaction. Correctness therefore rests on three properties rather than on a
distributed commit:

* deterministic point identity, so a replayed batch overwrites instead of duplicating;
* read-back reconciliation against the expected set recorded in PostgreSQL;
* activation as a PostgreSQL state change that happens only after that reconciliation, leaving the
  previous active index untouched when a replacement fails.
"""

import time
from contextlib import nullcontext
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import UUID, uuid4, uuid5

from sqlalchemy import func, select, update
from sqlalchemy.orm import Session, sessionmaker

from app.core.embedding_config import EmbeddingConfig, IndexConfig
from app.core.errors import DomainError
from app.embeddings.errors import MESSAGES, EmbeddingCancelled, EmbeddingError
from app.embeddings.inputs import ChunkSource, build
from app.embeddings.medcpt import vector_checksum
from app.embeddings.model import EmbeddingInput, EmbeddingModel, EmbeddingVector
from app.embeddings.validation import (
    EMBEDDING_INPUT_TOO_LONG,
    INDEX_RECONCILIATION_FAILED,
    ExpectedPoint,
    Finding,
    ObservedPoint,
    check_vector,
    reconcile,
)
from app.embeddings.validation import (
    MESSAGES as FINDING_MESSAGES,
)
from app.ingestion.state import transition
from app.models.chunking import ChunkRun
from app.models.documents import Document, DocumentVersion, IngestionJob, OutboxMessage
from app.models.embeddings import (
    ChunkEmbedding,
    EmbeddingRun,
    EmbeddingVersion,
    IndexRun,
    IndexValidationFinding,
)
from app.models.enums import Status
from app.observability.ingestion import audit, phase_event
from app.repositories.embeddings import load_sources, payload_for
from app.security.auth import Principal
from app.vectorindex.model import VectorPoint, VectorSchema

# Deterministic namespace so a chunk maps to the same index point on every run and every host.
POINT_NAMESPACE = UUID("6f9619ff-8b86-d011-b42d-00cf4fc964ff")


def point_id(chunk_id: UUID, vector_name: str) -> UUID:
    """Stable point identity derived from application identity, never generated by the index."""
    return uuid5(POINT_NAMESPACE, f"{chunk_id}/{vector_name}")


class EmbeddingService:
    def __init__(
        self,
        sessions: sessionmaker[Session],
        config: EmbeddingConfig,
        index_config: IndexConfig,
        model_factory: Any = None,
        index_factory: Any = None,
        worker_identity: str = "celery-embedder",
    ) -> None:
        self.sessions = sessions
        self.config = config
        self.index_config = index_config
        self._model_factory = model_factory
        self._index_factory = index_factory
        self.worker = worker_identity

    # ------------------------------------------------------------------ helpers

    def model(self) -> EmbeddingModel:
        if self._model_factory is None:
            raise EmbeddingError("EMBEDDING_MODEL_LOAD_FAILED")
        built: EmbeddingModel = self._model_factory()
        return built

    def index(self) -> Any:
        if self._index_factory is None:
            raise EmbeddingError("VECTOR_INDEX_UNAVAILABLE")
        return self._index_factory()

    def schema(self, collection: str) -> VectorSchema:
        return VectorSchema(
            collection=collection,
            vector_name=self.index_config.dense_vector_name,
            dimension=self.config.embedding_dimension,
            distance=self.config.distance_metric,
            payload_indexes=self.index_config.payload_indexes,
            tenant_key=self.index_config.tenant_payload_key,
        )

    def locked(
        self, session: Session, job_id: UUID
    ) -> tuple[Document, DocumentVersion, IngestionJob]:
        job = session.get(IngestionJob, job_id)
        if job is None:
            raise EmbeddingError("EMBEDDING_SOURCE_NOT_READY")
        version = session.get(DocumentVersion, job.document_version_id)
        if version is None:
            raise EmbeddingError("EMBEDDING_SOURCE_NOT_READY")
        document = session.get(Document, version.document_id, with_for_update=True)
        if document is None:
            raise EmbeddingError("EMBEDDING_SOURCE_NOT_READY")
        session.refresh(job, with_for_update=True)
        return document, version, job

    def embedding_version(self, session: Session, config: EmbeddingConfig) -> EmbeddingVersion:
        """Find or create the vector-space identity for this configuration.

        Keyed on the semantics fingerprint, not on the whole policy: changing a batch size does
        not change what a vector means, and must not fragment the vector space.
        """
        fingerprint = config.semantics_fingerprint
        existing = session.scalar(
            select(EmbeddingVersion).where(EmbeddingVersion.semantics_fingerprint == fingerprint)
        )
        if existing is not None:
            return existing
        version = EmbeddingVersion(
            id=uuid4(),
            model_provider=config.model_provider,
            model_id=config.model_id,
            model_revision=config.model_revision,
            tokenizer_revision=config.tokenizer_revision,
            model_checksum=config.model_checksum,
            embedding_dimension=config.embedding_dimension,
            pooling_strategy=config.pooling_strategy,
            normalization=config.normalization,
            distance_metric=config.distance_metric,
            max_input_tokens=config.max_input_tokens,
            dtype=config.dtype,
            input_builder_version=config.input_builder_version,
            configuration_version=config.version,
            semantics_fingerprint=fingerprint,
            policy_fingerprint=config.fingerprint,
            config_snapshot=config.model_dump(mode="json"),
            library_versions={},
        )
        session.add(version)
        session.flush()
        return version

    # ------------------------------------------------------------------ scheduling

    def schedule(
        self,
        job_id: UUID,
        force: bool = False,
        policy: EmbeddingConfig | None = None,
        _session: Session | None = None,
    ) -> UUID | None:
        config = policy or self.config
        with self.sessions.begin() if _session is None else nullcontext(_session) as session:
            document, version, job = self.locked(session, job_id)
            if document.archived_at or job.status != Status.READY_FOR_EMBEDDING:
                return None
            existing = session.scalar(
                select(EmbeddingRun).where(
                    EmbeddingRun.ingestion_job_id == job.id,
                    EmbeddingRun.generation == job.retry_count,
                )
            )
            if existing:
                return existing.id
            dataset = session.scalar(
                select(ChunkRun)
                .where(
                    ChunkRun.document_version_id == version.id,
                    ChunkRun.tenant_id == version.tenant_id,
                    ChunkRun.is_active.is_(True),
                )
                .with_for_update()
            )
            if (
                dataset is None
                or dataset.status != "SUCCEEDED"
                or dataset.validation_result not in {"PASS", "PASS_WITH_WARNINGS"}
            ):
                transition(
                    session,
                    job,
                    version,
                    Status.FAILED,
                    None,
                    service=self.worker,
                    error_code="EMBEDDING_SOURCE_NOT_READY",
                    error_message=MESSAGES["EMBEDDING_SOURCE_NOT_READY"][0],
                )
                return None
            embedding_version = self.embedding_version(session, config)
            run = EmbeddingRun(
                id=uuid4(),
                tenant_id=job.tenant_id,
                document_id=document.id,
                document_version_id=version.id,
                chunk_run_id=dataset.id,
                embedding_version_id=embedding_version.id,
                ingestion_job_id=job.id,
                generation=job.retry_count,
                status="PENDING",
                force=force,
                policy_fingerprint=config.fingerprint,
                config_snapshot=config.model_dump(mode="json"),
                correlation_id=job.correlation_id,
            )
            session.add(run)
            session.flush()
            session.add(
                OutboxMessage(
                    job_id=job.id,
                    generation=job.retry_count,
                    kind="EMBEDDING",
                    embedding_run_id=run.id,
                )
            )
            audit(session, job.tenant_id, None, "EMBEDDING_RUN_CREATED", run.id, job.correlation_id)
            return run.id

    def request(
        self,
        actor: Principal,
        job_id: UUID,
        correlation_id: UUID,
        force: bool = False,
        config: EmbeddingConfig | None = None,
    ) -> UUID | None:
        actor.require("ingestion:reembed")
        with self.sessions.begin() as session:
            document, version, job = self.locked(session, job_id)
            if job.tenant_id != actor.tenant_id:
                raise DomainError("INGESTION_JOB_NOT_FOUND", "Ingestion job not found.", 404)
            if document.archived_at:
                raise DomainError(
                    "DOCUMENT_ARCHIVED", "Archived documents cannot be re-embedded.", 409
                )
            if job.status not in {
                Status.READY_FOR_EMBEDDING,
                Status.READY_FOR_RETRIEVAL,
                Status.RETRIEVAL_READY,
                Status.NEEDS_REVIEW,
                Status.FAILED,
            }:
                raise DomainError(
                    "INGESTION_INVALID_TRANSITION",
                    "This job cannot be re-embedded in its current state.",
                    409,
                )
            job.correlation_id = correlation_id
            if job.status != Status.READY_FOR_EMBEDDING:
                transition(
                    session,
                    job,
                    version,
                    Status.READY_FOR_EMBEDDING,
                    actor.user_id,
                    reembed=True,
                )
            audit(
                session,
                job.tenant_id,
                actor.user_id,
                "EMBEDDING_REPROCESS_REQUESTED",
                job.id,
                correlation_id,
                {"force": force, "configuration_version": (config or self.config).version},
            )
            return self.schedule(job_id, force, config, _session=session)

    # ------------------------------------------------------------------ claim and fence

    def _claim(self, run_id: UUID) -> tuple[UUID, EmbeddingConfig] | None:
        with self.sessions.begin() as session:
            run = session.get(EmbeddingRun, run_id)
            if run is None:
                return None
            document, version, job = self.locked(session, run.ingestion_job_id)
            session.refresh(run, with_for_update=True)
            if run.status != "PENDING":
                return None
            if (
                document.archived_at
                or job.status != Status.READY_FOR_EMBEDDING
                or job.retry_count != run.generation
            ):
                run.status = "CANCELLED"
                run.completed_at = datetime.now(UTC)
                return None
            config = EmbeddingConfig.model_validate(run.config_snapshot)
            token = uuid4()
            run.status = "RUNNING"
            run.started_at = datetime.now(UTC)
            run.lease_token = token
            run.lease_expires_at = datetime.now(UTC) + timedelta(seconds=config.lease_seconds)
            run.worker_identity = self.worker
            transition(session, job, version, Status.EMBEDDING, None, service=self.worker)
            phase_event("EMBEDDING_RUN_STARTED", run.correlation_id, run_id)
            return token, config

    def _fenced(
        self, session: Session, run_id: UUID, token: UUID
    ) -> tuple[EmbeddingRun, DocumentVersion, IngestionJob]:
        run = session.get(EmbeddingRun, run_id)
        if run is None:
            raise EmbeddingCancelled()
        document, version, job = self.locked(session, run.ingestion_job_id)
        session.refresh(run, with_for_update=True)
        dataset = session.get(ChunkRun, run.chunk_run_id)
        if (
            run.status != "RUNNING"
            or run.lease_token != token
            or not run.lease_expires_at
            or run.lease_expires_at < datetime.now(UTC)
            or job.status not in {Status.EMBEDDING, Status.INDEXING, Status.VERIFYING_INDEX}
            or job.retry_count != run.generation
            or document.archived_at
        ):
            raise EmbeddingCancelled()
        if dataset is None or not dataset.is_active:
            raise EmbeddingError("EMBEDDING_SOURCE_NOT_READY")
        return run, version, job

    # ------------------------------------------------------------------ execution

    def run(self, run_id: UUID) -> None:
        claim = self._claim(run_id)
        if claim is None:
            return
        token, config = claim
        started = time.perf_counter()
        last_check = 0.0

        def checkpoint() -> None:
            nonlocal last_check
            elapsed = time.perf_counter() - started
            if elapsed > config.timeout_seconds:
                raise EmbeddingError("EMBEDDING_TIMEOUT")
            if elapsed - last_check >= 2:
                with self.sessions.begin() as session:
                    self._fenced(session, run_id, token)
                last_check = elapsed

        try:
            self._execute(run_id, token, config, checkpoint, started)
        except EmbeddingCancelled:
            self._fail(run_id, token, None, cancelled=True)
        except EmbeddingError as exc:
            self._fail(run_id, token, exc.code, detail=exc.details)
        except Exception:
            self._fail(run_id, token, "EMBEDDING_PERSISTENCE_FAILED")

    def _execute(
        self,
        run_id: UUID,
        token: UUID,
        config: EmbeddingConfig,
        checkpoint: Any,
        started: float,
    ) -> None:
        with self.sessions() as session:
            run = session.get(EmbeddingRun, run_id)
            assert run is not None
            sources, chunks, document, _ = load_sources(session, run, config)
            correlation = run.correlation_id
            payloads = {
                chunk_id: payload_for(chunk, document, run) for chunk_id, chunk in chunks.items()
            }
            reusable = self._reusable(session, run, config, sources) if not run.force else {}

        model = self.model()
        specification = model.specification
        if specification.model_revision != config.model_revision:
            raise EmbeddingError("EMBEDDING_MODEL_REVISION_MISMATCH")
        if specification.dimension != config.embedding_dimension:
            raise EmbeddingError("EMBEDDING_DIMENSION_MISMATCH")

        phase_event("EMBEDDING_INPUTS_BUILT", correlation, run_id)
        inputs = tuple(build(source, config) for source in sources)
        findings: list[Finding] = []
        vectors, reused = self._embed(inputs, reusable, model, config, checkpoint, findings)
        phase_event("EMBEDDING_VECTORS_COMPLETE", correlation, run_id)

        self._persist_embeddings(
            run_id, token, config, inputs, vectors, reused, findings, specification
        )
        phase_event("INDEX_STAGING_STARTED", correlation, run_id)
        self._index(run_id, token, config, vectors, reused, payloads, checkpoint, started)

    def _reusable(
        self,
        session: Session,
        run: EmbeddingRun,
        config: EmbeddingConfig,
        sources: tuple[ChunkSource, ...],
    ) -> dict[UUID, ChunkEmbedding]:
        """Vectors from an earlier run that provably correspond to the same input.

        The match is on the exact input hash *and* the same embedding version and tenant. Two
        chunks whose text merely looks alike never share a vector.
        """
        if not config.reuse_existing_embeddings or not sources:
            return {}
        hashes = {build(source, config).input_hash: source.chunk_id for source in sources}
        rows = session.execute(
            select(ChunkEmbedding, EmbeddingRun.embedding_version_id)
            .join(EmbeddingRun, EmbeddingRun.id == ChunkEmbedding.embedding_run_id)
            .where(
                ChunkEmbedding.tenant_id == run.tenant_id,
                ChunkEmbedding.input_hash.in_(list(hashes)),
                ChunkEmbedding.vector_name == self.index_config.dense_vector_name,
                EmbeddingRun.embedding_version_id == run.embedding_version_id,
                EmbeddingRun.status == "SUCCEEDED",
            )
        ).all()
        found: dict[UUID, ChunkEmbedding] = {}
        for embedding, _ in rows:
            chunk_id = hashes.get(embedding.input_hash)
            if chunk_id is not None and chunk_id == embedding.chunk_id:
                found.setdefault(chunk_id, embedding)
        return found

    def _embed(
        self,
        inputs: tuple[EmbeddingInput, ...],
        reusable: dict[UUID, ChunkEmbedding],
        model: EmbeddingModel,
        config: EmbeddingConfig,
        checkpoint: Any,
        findings: list[Finding],
    ) -> tuple[dict[UUID, EmbeddingVector], dict[UUID, ChunkEmbedding]]:
        pending = [value for value in inputs if value.chunk_id not in reusable]
        reused = {
            value.chunk_id: reusable[value.chunk_id]
            for value in inputs
            if value.chunk_id in reusable
        }
        if not pending:
            return {}, reused

        # Token limits are measured for the whole set first, so an over-long chunk is reported as
        # a finding naming the chunk rather than surfacing as an opaque mid-run failure.
        measured = model.measure(tuple(pending))
        over = [item for item in measured if item.exceeds_limit]
        if over:
            for item in over:
                findings.append(
                    Finding(
                        severity="CRITICAL",
                        code=EMBEDDING_INPUT_TOO_LONG,
                        message=FINDING_MESSAGES[EMBEDDING_INPUT_TOO_LONG],
                        chunk_id=item.chunk_id,
                        details={
                            "token_count": item.token_count,
                            "limit": config.max_input_tokens,
                            "action": "rechunk the document; nothing was truncated",
                        },
                    )
                )
            raise EmbeddingError(
                "EMBEDDING_INPUT_TOO_LONG",
                {
                    "chunk_ids": [str(item.chunk_id) for item in over][:20],
                    "count": len(over),
                    "limit": config.max_input_tokens,
                },
            )

        produced: dict[UUID, EmbeddingVector] = {}
        for start in range(0, len(pending), config.batch_size):
            checkpoint()
            batch = tuple(pending[start : start + config.batch_size])
            for vector in model.embed_documents(batch):
                problems = check_vector(vector, config)
                if problems:
                    findings.extend(problems)
                    raise EmbeddingError(
                        problems[0].code if problems[0].code in MESSAGES else "EMBEDDING_NON_FINITE"
                    )
                produced[vector.chunk_id] = vector
        return produced, reused

    def _persist_embeddings(
        self,
        run_id: UUID,
        token: UUID,
        config: EmbeddingConfig,
        inputs: tuple[EmbeddingInput, ...],
        vectors: dict[UUID, EmbeddingVector],
        reused: dict[UUID, ChunkEmbedding],
        findings: list[Finding],
        specification: Any,
    ) -> None:
        with self.sessions.begin() as session:
            run, version, job = self._fenced(session, run_id, token)
            name = self.index_config.dense_vector_name
            for value in inputs:
                previous = reused.get(value.chunk_id)
                vector = vectors.get(value.chunk_id)
                if vector is None and previous is None:
                    continue
                session.add(
                    ChunkEmbedding(
                        id=uuid5(run_id, str(value.chunk_id) + "/" + name),
                        tenant_id=run.tenant_id,
                        embedding_run_id=run_id,
                        chunk_run_id=run.chunk_run_id,
                        chunk_id=value.chunk_id,
                        point_id=point_id(value.chunk_id, name),
                        vector_name=name,
                        input_hash=value.input_hash,
                        vector_checksum=(
                            vector.checksum if vector else previous.vector_checksum  # type: ignore[union-attr]
                        ),
                        dimension=config.embedding_dimension,
                        token_count=vector.token_count if vector else previous.token_count,  # type: ignore[union-attr]
                        vector_norm=vector.norm if vector else previous.vector_norm,  # type: ignore[union-attr]
                        truncated=False,
                        reused=vector is None,
                    )
                )
            run.eligible_chunk_count = len(inputs)
            run.embedded_chunk_count = len(vectors) + len(reused)
            run.reused_chunk_count = len(reused)
            run.failed_chunk_count = 0
            run.input_fingerprint = _fingerprint(inputs)
            session.flush()
            self._record(session, findings, embedding_run_id=run_id)
            embedding_version = session.get(EmbeddingVersion, run.embedding_version_id)
            if embedding_version is not None and not embedding_version.library_versions:
                embedding_version.library_versions = dict(specification.library_versions)
            transition(session, job, version, Status.INDEXING, None, service=self.worker)
            _ = version

    # ------------------------------------------------------------------ indexing

    def _index(
        self,
        run_id: UUID,
        token: UUID,
        config: EmbeddingConfig,
        vectors: dict[UUID, EmbeddingVector],
        reused: dict[UUID, ChunkEmbedding],
        payloads: dict[UUID, dict[str, Any]],
        checkpoint: Any,
        started: float,
    ) -> None:
        index = self.index()
        collection = self.index_config.collection(config.semantics_fingerprint)
        schema = self.schema(collection)
        index.ensure_schema(schema)

        with self.sessions.begin() as session:
            run, _, _ = self._fenced(session, run_id, token)
            attempt = (
                session.scalar(
                    select(func.count())
                    .select_from(IndexRun)
                    .where(IndexRun.embedding_run_id == run_id)
                )
                or 0
            )
            index_run = IndexRun(
                id=uuid4(),
                tenant_id=run.tenant_id,
                document_id=run.document_id,
                document_version_id=run.document_version_id,
                chunk_run_id=run.chunk_run_id,
                embedding_run_id=run_id,
                embedding_version_id=run.embedding_version_id,
                attempt=int(attempt),
                physical_collection=collection,
                alias=self.index_config.alias,
                vector_name=self.index_config.dense_vector_name,
                schema_version=self.index_config.schema_version,
                status="STAGING",
                expected_point_count=len(payloads),
                policy_fingerprint=self.index_config.fingerprint,
                config_snapshot=self.index_config.model_dump(mode="json"),
                started_at=datetime.now(UTC),
                correlation_id=run.correlation_id,
            )
            session.add(index_run)
            session.flush()
            index_run_id = index_run.id
            correlation = run.correlation_id
            expected = [
                ExpectedPoint(
                    point_id=row.point_id,
                    chunk_id=row.chunk_id,
                    vector_checksum=row.vector_checksum,
                    payload={
                        **payloads[row.chunk_id],
                        "index_run_id": str(index_run.id),
                    },
                )
                for row in session.scalars(
                    select(ChunkEmbedding).where(ChunkEmbedding.embedding_run_id == run_id)
                )
                if row.chunk_id in payloads
            ]

        # Points carry the vectors this run produced. A reused embedding keeps its recorded
        # checksum, so its vector must be re-read from the index rather than invented here.
        missing_reuse = [
            chunk_id for chunk_id in reused if chunk_id not in vectors and chunk_id in payloads
        ]
        recovered = self._recover(index, schema, reused, missing_reuse)
        points = []
        for item in expected:
            values = (
                vectors[item.chunk_id].values
                if item.chunk_id in vectors
                else recovered.get(item.chunk_id)
            )
            if values is None:
                raise EmbeddingError(
                    "VECTOR_RECONCILIATION_FAILED", {"chunk_id": str(item.chunk_id)}
                )
            points.append(
                VectorPoint(
                    point_id=item.point_id,
                    chunk_id=item.chunk_id,
                    vector=values,
                    payload=item.payload,
                )
            )

        uploaded = 0
        batches = 0
        size = self.index_config.upsert_batch_size
        for start in range(0, len(points), size):
            checkpoint()
            uploaded += index.upsert(schema, tuple(points[start : start + size]))
            batches += 1

        with self.sessions.begin() as session:
            run, version, job = self._fenced(session, run_id, token)
            staged = session.get(IndexRun, index_run_id)
            assert staged is not None
            staged.indexed_point_count = uploaded
            staged.upsert_batches = batches
            staged.status = "VERIFYING"
            transition(session, job, version, Status.VERIFYING_INDEX, None, service=self.worker)
        phase_event("INDEX_VERIFICATION_STARTED", correlation, index_run_id)

        outcome = self._verify(index, schema, tuple(expected), run_id, config)
        self._finalize(
            run_id,
            index_run_id,
            token,
            index,
            schema,
            outcome,
            uploaded,
            batches,
            int((time.perf_counter() - started) * 1000),
        )

    def _recover(
        self,
        index: Any,
        schema: VectorSchema,
        reused: dict[UUID, ChunkEmbedding],
        missing: list[UUID],
    ) -> dict[UUID, tuple[float, ...]]:
        """Read reused vectors back from the index so a reused point is written from real data."""
        if not missing:
            return {}
        wanted = {reused[chunk_id].point_id: chunk_id for chunk_id in missing}
        stored = index.retrieve(schema, tuple(wanted), True)
        recovered: dict[UUID, tuple[float, ...]] = {}
        for record in stored:
            chunk_id = wanted.get(record.point_id)
            if chunk_id is None or record.vector is None:
                continue
            if vector_checksum(record.vector) == reused[chunk_id].vector_checksum:
                recovered[chunk_id] = record.vector
        return recovered

    def _verify(
        self,
        index: Any,
        schema: VectorSchema,
        expected: tuple[ExpectedPoint, ...],
        run_id: UUID,
        config: EmbeddingConfig,
    ) -> Any:
        selector = {"embedding_run_id": str(run_id)}
        index_ids = index.scroll_ids(schema, selector)
        observed: list[ObservedPoint] = []
        ids = [item.point_id for item in expected]
        size = self.index_config.verify_batch_size
        for start in range(0, len(ids), size):
            for record in index.retrieve(
                schema, tuple(ids[start : start + size]), self.index_config.verify_vectors
            ):
                observed.append(
                    ObservedPoint(
                        point_id=record.point_id, vector=record.vector, payload=record.payload
                    )
                )
        return reconcile(
            expected,
            tuple(observed),
            index_ids,
            config,
            vector_checksum,
            self.index_config.verify_vectors,
        )

    def _finalize(
        self,
        run_id: UUID,
        index_run_id: UUID,
        token: UUID,
        index: Any,
        schema: VectorSchema,
        outcome: Any,
        uploaded: int,
        batches: int,
        duration: int,
    ) -> None:
        with self.sessions.begin() as session:
            run, version, job = self._fenced(session, run_id, token)
            staged = session.get(IndexRun, index_run_id)
            assert staged is not None
            self._record(
                session, list(outcome.findings), embedding_run_id=run_id, index_run_id=index_run_id
            )
            staged.verified_point_count = outcome.verified
            staged.completed_at = datetime.now(UTC)
            staged.duration_ms = duration
            staged.metrics = {
                "expected_points": outcome.expected,
                "observed_points": outcome.observed,
                "verified_points": outcome.verified,
                "upsert_batches": batches,
                "uploaded_points": uploaded,
                "findings": len(outcome.findings),
            }
            if not outcome.ok:
                # The previous active index is deliberately left alone: a failed replacement must
                # not remove the corpus that was already verified.
                staged.status = "FAILED"
                staged.is_active = False
                staged.error_code = "VECTOR_RECONCILIATION_FAILED"
                staged.error_message = MESSAGES["VECTOR_RECONCILIATION_FAILED"][0]
                run.status = "FAILED"
                run.is_active = False
                run.error_code = "VECTOR_RECONCILIATION_FAILED"
                run.error_message = staged.error_message
                run.completed_at = datetime.now(UTC)
                run.lease_expires_at = None
                run.duration_ms = duration
                transition(
                    session,
                    job,
                    version,
                    Status.FAILED,
                    None,
                    service=self.worker,
                    error_code=run.error_code,
                    error_message=run.error_message,
                )
                audit(
                    session,
                    run.tenant_id,
                    None,
                    "INDEX_RUN_FAILED",
                    index_run_id,
                    run.correlation_id,
                    {"findings": len(outcome.findings)},
                )
                return

            staged.status = "VERIFIED"
            run.status = "SUCCEEDED"
            run.completed_at = datetime.now(UTC)
            run.lease_expires_at = None
            run.duration_ms = duration
            run.metrics = {
                "eligible_chunks": run.eligible_chunk_count,
                "embedded_chunks": run.embedded_chunk_count,
                "reused_chunks": run.reused_chunk_count,
                "indexed_points": uploaded,
                "verified_points": outcome.verified,
                "upsert_batches": batches,
                "collection": staged.physical_collection,
                "vector_name": staged.vector_name,
            }
            # Activation: supersede the previous active rows, then mark these active. Both happen
            # in this one PostgreSQL transaction, which is the authoritative pointer M5 reads.
            session.execute(
                update(IndexRun)
                .where(
                    IndexRun.document_version_id == run.document_version_id,
                    IndexRun.is_active.is_(True),
                    IndexRun.id != index_run_id,
                )
                .values(is_active=False, status="SUPERSEDED")
            )
            session.execute(
                update(EmbeddingRun)
                .where(
                    EmbeddingRun.document_version_id == run.document_version_id,
                    EmbeddingRun.is_active.is_(True),
                    EmbeddingRun.id != run_id,
                )
                .values(is_active=False)
            )
            run.is_active = True
            staged.is_active = True
            staged.activated_at = datetime.now(UTC)
            transition(session, job, version, Status.READY_FOR_RETRIEVAL, None, service=self.worker)
            audit(
                session,
                run.tenant_id,
                None,
                "INDEX_RUN_ACTIVATED",
                index_run_id,
                run.correlation_id,
                {"points": outcome.verified, "collection": staged.physical_collection},
            )
            phase_event("INDEX_ACTIVATED", run.correlation_id, index_run_id)
        # The read alias follows the verified collection. Qdrant applies an alias change
        # atomically; if it fails the durable pointer above is still correct and M5 reads
        # PostgreSQL, so this is a convenience for operators rather than the source of truth.
        try:
            index.set_alias(self.index_config.alias, schema.collection)
        except EmbeddingError:
            pass

    # ------------------------------------------------------------------ findings and failure

    def _record(
        self,
        session: Session,
        findings: list[Finding],
        embedding_run_id: UUID | None = None,
        index_run_id: UUID | None = None,
    ) -> None:
        for finding in findings:
            session.add(
                IndexValidationFinding(
                    embedding_run_id=embedding_run_id,
                    index_run_id=index_run_id,
                    chunk_id=finding.chunk_id,
                    severity=finding.severity,
                    code=finding.code,
                    message=finding.message,
                    details=finding.details,
                )
            )

    def _fail(
        self,
        run_id: UUID,
        token: UUID,
        code: str | None,
        cancelled: bool = False,
        detail: dict[str, Any] | None = None,
    ) -> None:
        with self.sessions.begin() as session:
            run = session.get(EmbeddingRun, run_id)
            if run is None:
                return
            _, version, job = self.locked(session, run.ingestion_job_id)
            session.refresh(run, with_for_update=True)
            if run.status not in {"PENDING", "RUNNING"} or run.lease_token != token:
                return
            run.status = "CANCELLED" if cancelled else "FAILED"
            run.is_active = False
            run.completed_at = datetime.now(UTC)
            run.lease_expires_at = None
            run.error_code = code
            run.error_message = MESSAGES[code][0] if code else None
            session.execute(
                update(IndexRun)
                .where(
                    IndexRun.embedding_run_id == run_id,
                    IndexRun.status.in_(("STAGING", "VERIFYING")),
                )
                .values(
                    status="CANCELLED" if cancelled else "FAILED",
                    is_active=False,
                    error_code=code,
                    completed_at=datetime.now(UTC),
                )
            )
            if detail:
                session.add(
                    IndexValidationFinding(
                        embedding_run_id=run_id,
                        index_run_id=None,
                        chunk_id=None,
                        severity="CRITICAL",
                        code=code or INDEX_RECONCILIATION_FAILED,
                        message=run.error_message or FINDING_MESSAGES[INDEX_RECONCILIATION_FAILED],
                        details={key: value for key, value in detail.items() if key != "retryable"},
                    )
                )
            if (
                job.status in {Status.EMBEDDING, Status.INDEXING, Status.VERIFYING_INDEX}
                and job.retry_count == run.generation
            ):
                transition(
                    session,
                    job,
                    version,
                    Status.CANCELLED if cancelled else Status.FAILED,
                    None,
                    service=self.worker,
                    error_code=run.error_code,
                    error_message=run.error_message,
                )
            audit(
                session,
                run.tenant_id,
                None,
                "EMBEDDING_RUN_CANCELLED" if cancelled else "EMBEDDING_RUN_FAILED",
                run_id,
                run.correlation_id,
                {"code": code},
            )

    # ------------------------------------------------------------------ sweeping

    def sweep(self) -> int:
        with self.sessions() as session:
            jobs = list(
                session.scalars(
                    select(IngestionJob.id)
                    .where(IngestionJob.status == Status.READY_FOR_EMBEDDING)
                    .limit(20)
                )
            )
            expired = list(
                session.execute(
                    select(EmbeddingRun.id, EmbeddingRun.lease_token).where(
                        EmbeddingRun.status == "RUNNING",
                        EmbeddingRun.lease_expires_at < datetime.now(UTC),
                    )
                )
            )
        for job_id in jobs:
            self.schedule(job_id)
        for run_id, token in expired:
            self._fail(run_id, token, "EMBEDDING_LEASE_EXPIRED")
        return len(jobs) + len(expired)


def _fingerprint(inputs: tuple[EmbeddingInput, ...]) -> str:
    import hashlib

    digest = hashlib.sha256()
    for value in sorted(inputs, key=lambda item: str(item.chunk_id)):
        digest.update(str(value.chunk_id).encode())
        digest.update(value.input_hash.encode())
    return digest.hexdigest()
