"""M1 document ingestion control plane

Revision ID: 0dd8e0dcb035
Revises:
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0dd8e0dcb035"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "users",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_users_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_users_id")),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("safe_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_audit_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "GUIDELINE",
                "REFERENCE_BOOK",
                "TEXTBOOK",
                "COURSE_MATERIAL",
                "QUESTION_BANK",
                "QUESTION_PAPER",
                "ANSWER_KEY",
                "OTHER",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("specialty", sa.String(length=120), nullable=True),
        sa.Column("subject", sa.String(length=120), nullable=True),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column(
            "authority_level",
            sa.Enum(
                "UNREVIEWED",
                "ASSESSMENT",
                "REFERENCE",
                "HIGH",
                name="authority_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id", "tenant_id"],
            ["users.id", "users.tenant_id"],
            name=op.f("fk_documents_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_documents_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_documents_id")),
    )
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "upload_intents",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("cleanup_required", sa.Boolean(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_upload_intents_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_upload_intents_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_intents")),
        sa.UniqueConstraint("object_key", name=op.f("uq_upload_intents_object_key")),
        sa.UniqueConstraint(
            "tenant_id", "actor_id", "idempotency_key", name=op.f("uq_upload_intents_tenant_id")
        ),
    )
    op.create_index(op.f("ix_upload_intents_sha256"), "upload_intents", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_upload_intents_tenant_id"), "upload_intents", ["tenant_id"], unique=False
    )
    op.create_table(
        "document_versions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("edition", sa.String(length=120), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("normalized_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=80), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_storage_key", sa.String(length=500), nullable=False),
        sa.Column("object_version_id", sa.String(length=200), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "ingestion_status",
            sa.Enum(
                "UPLOADED",
                "VALIDATING",
                "QUEUED",
                "PARSING",
                "NORMALIZING",
                "CHUNKING",
                "ENRICHING",
                "EMBEDDING",
                "INDEXING",
                "VERIFYING_INDEX",
                "READY",
                "FAILED",
                "QUARANTINED",
                "NEEDS_REVIEW",
                "CANCELLED",
                name="version_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("searchable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("NOT searchable", name=op.f("ck_document_versions_m1_never_searchable")),
        sa.CheckConstraint(
            "version_number > 0 AND file_size_bytes > 0",
            name=op.f("ck_document_versions_positive_version_file"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id", "tenant_id"],
            ["users.id", "users.tenant_id"],
            name=op.f("fk_document_versions_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "tenant_id"],
            ["documents.id", "documents.tenant_id"],
            name=op.f("fk_document_versions_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version_number", name=op.f("uq_document_versions_document_id")
        ),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_document_versions_id")),
        sa.UniqueConstraint(
            "object_storage_key", name=op.f("uq_document_versions_object_storage_key")
        ),
        sa.UniqueConstraint("tenant_id", "sha256", name=op.f("uq_document_versions_tenant_id")),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_versions_tenant_id"), "document_versions", ["tenant_id"], unique=False
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "VALIDATING",
                "QUEUED",
                "PARSING",
                "NORMALIZING",
                "CHUNKING",
                "ENRICHING",
                "EMBEDDING",
                "INDEXING",
                "VERIFYING_INDEX",
                "READY",
                "FAILED",
                "QUARANTINED",
                "NEEDS_REVIEW",
                "CANCELLED",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("current_stage", sa.String(length=40), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_version", sa.String(length=80), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queue_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_message", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "retry_count >= 0 AND retry_count <= max_retries",
            name=op.f("ck_ingestion_jobs_bounded_retries"),
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id", "tenant_id"],
            ["document_versions.id", "document_versions.tenant_id"],
            name=op.f("fk_ingestion_jobs_document_version_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id", "tenant_id"],
            ["users.id", "users.tenant_id"],
            name=op.f("fk_ingestion_jobs_requested_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint(
            "document_version_id", name=op.f("uq_ingestion_jobs_document_version_id")
        ),
    )
    op.create_index(op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_ingestion_jobs_tenant_id"), "ingestion_jobs", ["tenant_id"], unique=False
    )
    op.create_table(
        "ingestion_stage_events",
        sa.Column("ingestion_job_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=40), nullable=True),
        sa.Column("to_status", sa.String(length=40), nullable=False),
        sa.Column("service_identity", sa.String(length=120), nullable=False),
        sa.Column("retry_number", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.String(length=300), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_ingestion_stage_events_ingestion_job_id_ingestion_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_stage_events")),
    )
    op.create_index(
        op.f("ix_ingestion_stage_events_ingestion_job_id"),
        "ingestion_stage_events",
        ["ingestion_job_id"],
        unique=False,
    )
    op.create_table(
        "outbox_messages",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["ingestion_jobs.id"], name=op.f("fk_outbox_messages_job_id_ingestion_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("job_id", "generation", name=op.f("uq_outbox_messages_job_id")),
    )
    op.create_index(op.f("ix_outbox_messages_job_id"), "outbox_messages", ["job_id"], unique=False)
    # ### end Alembic commands ###

    install_guards()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_messages_job_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index(
        op.f("ix_ingestion_stage_events_ingestion_job_id"), table_name="ingestion_stage_events"
    )
    op.drop_table("ingestion_stage_events")
    op.drop_index(op.f("ix_ingestion_jobs_tenant_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_document_versions_tenant_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_upload_intents_tenant_id"), table_name="upload_intents")
    op.drop_index(op.f("ix_upload_intents_sha256"), table_name="upload_intents")
    op.drop_table("upload_intents")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION m1_job_guard(), m1_version_immutable(), m1_append_only()")


def install_guards() -> None:
    op.execute("""
    CREATE FUNCTION m1_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'Operational history is append-only'; END $$;
    """)
    for table in ("audit_events", "ingestion_stage_events"):
        op.execute(
            f"CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION m1_append_only()"
        )
    op.execute("""
    CREATE FUNCTION m1_version_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF ROW(NEW.document_id, NEW.tenant_id, NEW.version_number, NEW.edition,
             NEW.publication_year, NEW.original_filename, NEW.normalized_filename,
             NEW.mime_type, NEW.file_size_bytes, NEW.sha256, NEW.object_storage_key,
             NEW.object_version_id, NEW.created_by_user_id, NEW.created_at)
         IS DISTINCT FROM
         ROW(OLD.document_id, OLD.tenant_id, OLD.version_number, OLD.edition,
             OLD.publication_year, OLD.original_filename, OLD.normalized_filename,
             OLD.mime_type, OLD.file_size_bytes, OLD.sha256, OLD.object_storage_key,
             OLD.object_version_id, OLD.created_by_user_id, OLD.created_at)
      THEN RAISE EXCEPTION 'Original version identity is immutable'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER immutable_original BEFORE UPDATE ON document_versions
      FOR EACH ROW EXECUTE FUNCTION m1_version_immutable();
    """)
    op.execute("""
    CREATE FUNCTION m1_job_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'UPLOADED' OR NEW.retry_count <> 0
        THEN RAISE EXCEPTION 'Jobs must begin UPLOADED'; END IF;
        RETURN NEW;
      END IF;
      IF ROW(NEW.document_version_id, NEW.tenant_id, NEW.requested_by_user_id,
             NEW.configuration_version, NEW.config_snapshot, NEW.max_retries)
         IS DISTINCT FROM ROW(OLD.document_version_id, OLD.tenant_id, OLD.requested_by_user_id,
             OLD.configuration_version, OLD.config_snapshot, OLD.max_retries)
      THEN RAISE EXCEPTION 'Job provenance and configuration are immutable'; END IF;
      IF NEW.status IS DISTINCT FROM OLD.status THEN
        IF NOT (
          (OLD.status = 'UPLOADED' AND NEW.status IN ('VALIDATING', 'CANCELLED')) OR
          (OLD.status = 'VALIDATING' AND NEW.status IN
            ('QUEUED', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'QUEUED' AND NEW.status IN ('FAILED', 'QUARANTINED', 'CANCELLED')) OR
          (OLD.status IN ('FAILED', 'QUARANTINED', 'NEEDS_REVIEW') AND NEW.status = 'CANCELLED') OR
          (OLD.status = 'FAILED' AND NEW.status = 'VALIDATING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries))
        THEN RAISE EXCEPTION 'Illegal M1 ingestion transition'; END IF;
      END IF;
      IF NEW.retry_count <> OLD.retry_count AND NOT
        (OLD.status = 'FAILED' AND NEW.status = 'VALIDATING'
         AND NEW.retry_count = OLD.retry_count + 1)
      THEN RAISE EXCEPTION 'Retry count can change only on a retry'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER ingestion_transition_guard BEFORE INSERT OR UPDATE ON ingestion_jobs
      FOR EACH ROW EXECUTE FUNCTION m1_job_guard();
    """)
