"""m10 tenant configuration revisions

Revision ID: m10_configuration
Revises: m9_conversations
"""
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'm10_configuration'
down_revision = 'm9_conversations'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_revisions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runtime_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('desired_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('startup_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("result IN ('ACTIVE', 'PENDING_REBUILD')", name=op.f('ck_configuration_revisions_configuration_result')),
    sa.CheckConstraint('revision > 0', name=op.f('ck_configuration_revisions_positive_revision')),
    sa.ForeignKeyConstraint(['actor_id', 'tenant_id'], ['users.id', 'users.tenant_id'], name=op.f('fk_configuration_revisions_actor_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_configuration_revisions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_revisions')),
    sa.UniqueConstraint('tenant_id', 'revision', name=op.f('uq_configuration_revisions_tenant_id'))
    )
    op.create_index(op.f('ix_configuration_revisions_tenant_id'), 'configuration_revisions', ['tenant_id'], unique=False)
    op.add_column('conversation_turns', sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("""CREATE FUNCTION reject_configuration_revision_mutation() RETURNS trigger
    LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Configuration revisions are immutable'; END $$""")
    op.execute("""CREATE TRIGGER configuration_revision_immutable BEFORE UPDATE OR DELETE
    ON configuration_revisions FOR EACH ROW EXECUTE FUNCTION reject_configuration_revision_mutation()""")
    # ### end Alembic commands ###

def downgrade() -> None:
    connection = op.get_bind()
    populated = connection.scalar(sa.text("SELECT EXISTS (SELECT 1 FROM configuration_revisions) OR EXISTS (SELECT 1 FROM conversation_turns WHERE configuration_snapshot IS NOT NULL)"))
    if populated and os.environ.get("MEDRAG_ALLOW_CONFIGURATION_LOSS") != "1":
        raise RuntimeError("Configuration history exists; explicitly acknowledge loss before downgrade")
    op.execute("DROP TRIGGER configuration_revision_immutable ON configuration_revisions")
    op.execute("DROP FUNCTION reject_configuration_revision_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_turns', 'configuration_snapshot')
    op.drop_index(op.f('ix_configuration_revisions_tenant_id'), table_name='configuration_revisions')
    op.drop_table('configuration_revisions')
    # ### end Alembic commands ###
