"""m4 embeddings and vector index

Revision ID: m4_embeddings_and_index
Revises: m3_hierarchical_chunks
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'm4_embeddings_and_index'
down_revision = 'm3_hierarchical_chunks'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunk_runs_id_version_tenant', 'chunk_runs', ['id', 'document_version_id', 'tenant_id'])
    op.create_table('embedding_versions',
    sa.Column('model_provider', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('model_revision', sa.String(length=80), nullable=False),
    sa.Column('tokenizer_revision', sa.String(length=80), nullable=False),
    sa.Column('model_checksum', sa.String(length=64), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('pooling_strategy', sa.String(length=24), nullable=False),
    sa.Column('normalization', sa.String(length=24), nullable=False),
    sa.Column('distance_metric', sa.String(length=16), nullable=False),
    sa.Column('max_input_tokens', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(length=16), nullable=False),
    sa.Column('input_builder_version', sa.String(length=80), nullable=False),
    sa.Column('configuration_version', sa.String(length=80), nullable=False),
    sa.Column('semantics_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('policy_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('library_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("distance_metric IN ('DOT','COSINE','EUCLID')", name=op.f('ck_embedding_versions_embedding_distance_metric')),
    sa.CheckConstraint('embedding_dimension > 0', name=op.f('ck_embedding_versions_embedding_dimension_positive')),
    sa.CheckConstraint('max_input_tokens > 0', name=op.f('ck_embedding_versions_embedding_max_tokens_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_versions')),
    sa.UniqueConstraint('semantics_fingerprint', name='uq_embedding_versions_semantics')
    )
    op.create_index(op.f('ix_embedding_versions_model_id'), 'embedding_versions', ['model_id'], unique=False)
    op.create_table('embedding_runs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_run_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_version_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_job_id', sa.Uuid(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('force', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('eligible_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedded_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reused_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('policy_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('worker_identity', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT is_active OR (status = 'SUCCEEDED' AND failed_chunk_count = 0 AND embedded_chunk_count = eligible_chunk_count)", name=op.f('ck_embedding_runs_active_embedding_run_complete')),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','NEEDS_REVIEW','CANCELLED')", name=op.f('ck_embedding_runs_embedding_run_status')),
    sa.CheckConstraint('eligible_chunk_count >= 0 AND embedded_chunk_count >= 0 AND failed_chunk_count >= 0', name=op.f('ck_embedding_runs_embedding_counts_nonnegative')),
    sa.ForeignKeyConstraint(['chunk_run_id', 'document_version_id', 'tenant_id'], ['chunk_runs.id', 'chunk_runs.document_version_id', 'chunk_runs.tenant_id'], name=op.f('fk_embedding_runs_chunk_run_id_chunk_runs')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_embedding_runs_document_id_documents')),
    sa.ForeignKeyConstraint(['embedding_version_id'], ['embedding_versions.id'], name=op.f('fk_embedding_runs_embedding_version_id_embedding_versions')),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], name=op.f('fk_embedding_runs_ingestion_job_id_ingestion_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_runs')),
    sa.UniqueConstraint('id', 'chunk_run_id', 'tenant_id', name='uq_embedding_runs_id_chunk_run_tenant'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_embedding_runs_id_tenant'),
    sa.UniqueConstraint('ingestion_job_id', 'generation', name='uq_embedding_runs_job_generation')
    )
    op.create_index(op.f('ix_embedding_runs_chunk_run_id'), 'embedding_runs', ['chunk_run_id'], unique=False)
    op.create_index(op.f('ix_embedding_runs_document_version_id'), 'embedding_runs', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_embedding_runs_embedding_version_id'), 'embedding_runs', ['embedding_version_id'], unique=False)
    op.create_index(op.f('ix_embedding_runs_ingestion_job_id'), 'embedding_runs', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_embedding_runs_lease_expires_at'), 'embedding_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_embedding_runs_status'), 'embedding_runs', ['status'], unique=False)
    op.create_index(op.f('ix_embedding_runs_tenant_id'), 'embedding_runs', ['tenant_id'], unique=False)
    op.create_index('uq_embedding_run_active_version', 'embedding_runs', ['document_version_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('uq_embedding_run_pending_version', 'embedding_runs', ['document_version_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING','RUNNING')"))
    op.create_table('index_runs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_run_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_run_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_version_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('physical_collection', sa.String(length=120), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('vector_name', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expected_point_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('indexed_point_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_point_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('upsert_batches', sa.Integer(), server_default='0', nullable=False),
    sa.Column('policy_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT is_active OR (status = 'VERIFIED' AND verified_point_count = expected_point_count AND indexed_point_count = expected_point_count)", name=op.f('ck_index_runs_active_index_run_verified')),
    sa.CheckConstraint("status IN ('STAGING','VERIFYING','VERIFIED','FAILED','CANCELLED','SUPERSEDED')", name=op.f('ck_index_runs_index_run_status')),
    sa.CheckConstraint('expected_point_count >= 0 AND indexed_point_count >= 0 AND verified_point_count >= 0', name=op.f('ck_index_runs_index_counts_nonnegative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_index_runs_document_id_documents')),
    sa.ForeignKeyConstraint(['embedding_run_id', 'tenant_id'], ['embedding_runs.id', 'embedding_runs.tenant_id'], name=op.f('fk_index_runs_embedding_run_id_embedding_runs')),
    sa.ForeignKeyConstraint(['embedding_version_id'], ['embedding_versions.id'], name=op.f('fk_index_runs_embedding_version_id_embedding_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_runs')),
    sa.UniqueConstraint('embedding_run_id', 'attempt', name='uq_index_runs_embedding_run_attempt'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_index_runs_id_tenant')
    )
    op.create_index(op.f('ix_index_runs_document_version_id'), 'index_runs', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_index_runs_embedding_run_id'), 'index_runs', ['embedding_run_id'], unique=False)
    op.create_index(op.f('ix_index_runs_status'), 'index_runs', ['status'], unique=False)
    op.create_index(op.f('ix_index_runs_tenant_id'), 'index_runs', ['tenant_id'], unique=False)
    op.create_index('uq_index_run_active_version', 'index_runs', ['document_version_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('chunk_embeddings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('point_id', sa.Uuid(), nullable=False),
    sa.Column('vector_name', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('vector_checksum', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('vector_norm', sa.Float(), nullable=False),
    sa.Column('truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('NOT truncated', name=op.f('ck_chunk_embeddings_chunk_embedding_never_truncated')),
    sa.CheckConstraint('dimension > 0', name=op.f('ck_chunk_embeddings_chunk_embedding_dimension_positive')),
    sa.CheckConstraint('token_count >= 0', name=op.f('ck_chunk_embeddings_chunk_embedding_tokens_nonnegative')),
    sa.ForeignKeyConstraint(['chunk_id', 'chunk_run_id'], ['chunks.id', 'chunks.chunk_run_id'], name=op.f('fk_chunk_embeddings_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['embedding_run_id', 'tenant_id'], ['embedding_runs.id', 'embedding_runs.tenant_id'], name=op.f('fk_chunk_embeddings_embedding_run_id_embedding_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_embeddings')),
    sa.UniqueConstraint('embedding_run_id', 'chunk_id', 'vector_name', name='uq_chunk_embedding_identity'),
    sa.UniqueConstraint('embedding_run_id', 'point_id', name='uq_chunk_embedding_point')
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_embedding_run_id'), 'chunk_embeddings', ['embedding_run_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_input_hash'), 'chunk_embeddings', ['input_hash'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_tenant_id'), 'chunk_embeddings', ['tenant_id'], unique=False)
    op.create_table('index_validation_findings',
    sa.Column('embedding_run_id', sa.Uuid(), nullable=True),
    sa.Column('index_run_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','WARNING','ERROR','CRITICAL')", name=op.f('ck_index_validation_findings_index_finding_severity')),
    sa.CheckConstraint('embedding_run_id IS NOT NULL OR index_run_id IS NOT NULL', name=op.f('ck_index_validation_findings_index_finding_has_owner')),
    sa.ForeignKeyConstraint(['embedding_run_id'], ['embedding_runs.id'], name=op.f('fk_index_validation_findings_embedding_run_id_embedding_runs')),
    sa.ForeignKeyConstraint(['index_run_id'], ['index_runs.id'], name=op.f('fk_index_validation_findings_index_run_id_index_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_validation_findings'))
    )
    op.create_index(op.f('ix_index_validation_findings_code'), 'index_validation_findings', ['code'], unique=False)
    op.create_index(op.f('ix_index_validation_findings_embedding_run_id'), 'index_validation_findings', ['embedding_run_id'], unique=False)
    op.create_index(op.f('ix_index_validation_findings_index_run_id'), 'index_validation_findings', ['index_run_id'], unique=False)
    op.add_column('outbox_messages', sa.Column('embedding_run_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_outbox_messages_embedding_run_id_embedding_runs'), 'outbox_messages', 'embedding_runs', ['embedding_run_id'], ['id'])
    # ### end Alembic commands ###
    _m4_statuses()
    _install_guards()

def downgrade() -> None:
    _prepare_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_outbox_messages_embedding_run_id_embedding_runs'), 'outbox_messages', type_='foreignkey')
    op.drop_column('outbox_messages', 'embedding_run_id')
    op.drop_index(op.f('ix_index_validation_findings_index_run_id'), table_name='index_validation_findings')
    op.drop_index(op.f('ix_index_validation_findings_embedding_run_id'), table_name='index_validation_findings')
    op.drop_index(op.f('ix_index_validation_findings_code'), table_name='index_validation_findings')
    op.drop_table('index_validation_findings')
    op.drop_index(op.f('ix_chunk_embeddings_tenant_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_input_hash'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_embedding_run_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index('uq_index_run_active_version', table_name='index_runs', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_index_runs_tenant_id'), table_name='index_runs')
    op.drop_index(op.f('ix_index_runs_status'), table_name='index_runs')
    op.drop_index(op.f('ix_index_runs_embedding_run_id'), table_name='index_runs')
    op.drop_index(op.f('ix_index_runs_document_version_id'), table_name='index_runs')
    op.drop_table('index_runs')
    op.drop_index('uq_embedding_run_pending_version', table_name='embedding_runs', postgresql_where=sa.text("status IN ('PENDING','RUNNING')"))
    op.drop_index('uq_embedding_run_active_version', table_name='embedding_runs', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_embedding_runs_tenant_id'), table_name='embedding_runs')
    op.drop_index(op.f('ix_embedding_runs_status'), table_name='embedding_runs')
    op.drop_index(op.f('ix_embedding_runs_lease_expires_at'), table_name='embedding_runs')
    op.drop_index(op.f('ix_embedding_runs_ingestion_job_id'), table_name='embedding_runs')
    op.drop_index(op.f('ix_embedding_runs_embedding_version_id'), table_name='embedding_runs')
    op.drop_index(op.f('ix_embedding_runs_document_version_id'), table_name='embedding_runs')
    op.drop_index(op.f('ix_embedding_runs_chunk_run_id'), table_name='embedding_runs')
    op.drop_table('embedding_runs')
    op.drop_index(op.f('ix_embedding_versions_model_id'), table_name='embedding_versions')
    op.drop_table('embedding_versions')
    op.drop_constraint('uq_chunk_runs_id_version_tenant', 'chunk_runs', type_='unique')
    # ### end Alembic commands ###
    _restore_m3()


# The M3 graph plus the M4 stages, and the explicit re-embed edge. READY stays unreachable: it is
# reserved for a document that is genuinely answerable, which requires retrieval and grounding.
M4_JOB_GUARD = """
    CREATE OR REPLACE FUNCTION m1_job_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'UPLOADED' OR NEW.retry_count <> 0
        THEN RAISE EXCEPTION 'Jobs must begin UPLOADED'; END IF;
        RETURN NEW;
      END IF;
      IF ROW(NEW.document_version_id, NEW.tenant_id, NEW.requested_by_user_id,
             NEW.configuration_version, NEW.config_snapshot, NEW.max_retries)
         IS DISTINCT FROM ROW(OLD.document_version_id, OLD.tenant_id, OLD.requested_by_user_id,
             OLD.configuration_version, OLD.config_snapshot, OLD.max_retries)
      THEN RAISE EXCEPTION 'Job provenance and configuration are immutable'; END IF;
      IF NEW.status IS DISTINCT FROM OLD.status THEN
        IF NOT (
          (OLD.status = 'UPLOADED' AND NEW.status IN ('VALIDATING', 'CANCELLED')) OR
          (OLD.status = 'VALIDATING' AND NEW.status IN
            ('QUEUED', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'QUEUED' AND NEW.status IN
            ('PARSING', 'FAILED', 'QUARANTINED', 'CANCELLED')) OR
          (OLD.status = 'PARSING' AND NEW.status IN
            ('NORMALIZING', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'NORMALIZING' AND NEW.status IN
            ('ENRICHING', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'ENRICHING' AND NEW.status IN
            ('READY_FOR_CHUNKING', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'READY_FOR_CHUNKING' AND NEW.status IN
            ('CHUNKING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'CHUNKING' AND NEW.status IN
            ('VALIDATING_CHUNKS','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'VALIDATING_CHUNKS' AND NEW.status IN
            ('READY_FOR_EMBEDDING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'READY_FOR_EMBEDDING' AND NEW.status IN
            ('EMBEDDING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'EMBEDDING' AND NEW.status IN
            ('INDEXING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'INDEXING' AND NEW.status IN
            ('VERIFYING_INDEX','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'VERIFYING_INDEX' AND NEW.status IN
            ('READY_FOR_RETRIEVAL','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status IN ('FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'READY_FOR_CHUNKING',
                          'READY_FOR_EMBEDDING', 'READY_FOR_RETRIEVAL')
           AND NEW.status = 'CANCELLED') OR
          -- Retry, reparse, rechunk and re-embed all consume one unit of the same bounded budget,
          -- so no reprocessing path can loop without limit.
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_CHUNKING', 'READY_FOR_EMBEDDING',
                          'READY_FOR_RETRIEVAL')
           AND NEW.status = 'VALIDATING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries) OR
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_EMBEDDING', 'READY_FOR_RETRIEVAL')
           AND NEW.status = 'READY_FOR_CHUNKING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries) OR
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_RETRIEVAL')
           AND NEW.status = 'READY_FOR_EMBEDDING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries))
        THEN RAISE EXCEPTION 'Illegal ingestion transition'; END IF;
      END IF;
      IF NEW.retry_count <> OLD.retry_count AND NOT
        (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_CHUNKING', 'READY_FOR_EMBEDDING',
                        'READY_FOR_RETRIEVAL')
         AND NEW.status IN ('VALIDATING','READY_FOR_CHUNKING','READY_FOR_EMBEDDING')
         AND NEW.retry_count = OLD.retry_count + 1)
      THEN RAISE EXCEPTION 'Retry count can change only on a retry, reparse, rechunk or re-embed';
      END IF;
      RETURN NEW;
    END $$;
    """

M4_STATUS_ADDITIONS = ("READY_FOR_RETRIEVAL",)


def _rewrite_status_vocabulary(values: tuple[str, ...]) -> None:
    """Replace the permitted status set without touching the column type.

    READY_FOR_RETRIEVAL is 19 characters, exactly the width READY_FOR_EMBEDDING already forced, so
    no column needs widening. That matters: M3 attached triggers to `ingestion_jobs.status`, and
    PostgreSQL refuses to alter the type of a column a trigger definition depends on. Only the
    CHECK constraint changes here.
    """
    from migrations.versions.m2_document_parsing import STATUS_CONSTRAINTS
    listed = ", ".join(f"'{value}'" for value in values)
    for table, column, name in STATUS_CONSTRAINTS:
        op.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS "ck_{table}_{name}"')
        op.execute(
            f'ALTER TABLE {table} ADD CONSTRAINT "ck_{table}_{name}" '
            f"CHECK ({column} IN ({listed}))"
        )


M3_STATUSES: tuple[str, ...] = ()


def _m3_status_set() -> tuple[str, ...]:
    from migrations.versions.m2_document_parsing import M2_STATUSES
    return M2_STATUSES + ("VALIDATING_CHUNKS", "READY_FOR_EMBEDDING")


def _m4_statuses() -> None:
    _rewrite_status_vocabulary(_m3_status_set() + M4_STATUS_ADDITIONS)


def _restore_m3() -> None:
    from migrations.versions.m3_hierarchical_chunks_m3_hierarchical_chunks_and_source_ import (
        M3_JOB_GUARD,
    )
    _rewrite_status_vocabulary(_m3_status_set())
    op.execute(M3_JOB_GUARD)


def _prepare_downgrade() -> None:
    # Refuse rather than silently rewrite: an operator cancels these jobs deliberately.
    op.execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM ingestion_jobs
                 WHERE status IN ('EMBEDDING','INDEXING','VERIFYING_INDEX','READY_FOR_RETRIEVAL'))
      THEN RAISE EXCEPTION 'Cancel M4 jobs before downgrading; no states are silently rewritten';
      END IF;
    END $$;
    """)
    for table in ("embedding_runs", "index_runs", "chunk_embeddings", "index_validation_findings"):
        op.execute(f"DROP TRIGGER IF EXISTS m4_record_guard ON {table}")
    op.execute("DROP TRIGGER IF EXISTS m4_run_guard ON embedding_runs")
    op.execute("DROP TRIGGER IF EXISTS m4_index_guard ON index_runs")
    op.execute("DROP TRIGGER IF EXISTS m4_chunks_superseded ON chunk_runs")
    op.execute("DROP FUNCTION IF EXISTS m4_record_guard(), m4_run_guard(), m4_index_guard(), "
               "m4_invalidate_index()")
    # A stage-specific outbox message cannot survive the removal of its target table.
    op.execute("DELETE FROM outbox_messages WHERE kind = 'EMBEDDING'")


def _install_guards() -> None:
    op.execute(M4_JOB_GUARD)
    op.execute("""
    CREATE FUNCTION m4_run_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PENDING' OR NEW.is_active
        THEN RAISE EXCEPTION 'Embedding runs must begin pending and inactive'; END IF;
        -- The source chunk dataset must be the current, validated one for this exact version.
        IF NOT EXISTS (SELECT 1 FROM chunk_runs c
          WHERE c.id = NEW.chunk_run_id AND c.tenant_id = NEW.tenant_id
            AND c.document_version_id = NEW.document_version_id
            AND c.is_active AND c.status = 'SUCCEEDED'
            AND c.validation_result IN ('PASS','PASS_WITH_WARNINGS'))
        THEN RAISE EXCEPTION 'Embedding run source scope or readiness invalid'; END IF;
        RETURN NEW;
      END IF;
      IF ROW(NEW.tenant_id, NEW.document_id, NEW.document_version_id, NEW.chunk_run_id,
             NEW.embedding_version_id, NEW.ingestion_job_id, NEW.generation,
             NEW.policy_fingerprint, NEW.config_snapshot)
         IS DISTINCT FROM ROW(OLD.tenant_id, OLD.document_id, OLD.document_version_id,
             OLD.chunk_run_id, OLD.embedding_version_id, OLD.ingestion_job_id, OLD.generation,
             OLD.policy_fingerprint, OLD.config_snapshot)
      THEN RAISE EXCEPTION 'Embedding run identity is immutable'; END IF;
      IF OLD.status NOT IN ('PENDING','RUNNING') AND
        (to_jsonb(NEW) - 'is_active' - 'updated_at') IS DISTINCT FROM
        (to_jsonb(OLD) - 'is_active' - 'updated_at')
      THEN RAISE EXCEPTION 'Completed embedding runs are immutable'; END IF;
      IF NEW.is_active THEN
        IF NOT EXISTS (SELECT 1 FROM chunk_runs c WHERE c.id = NEW.chunk_run_id AND c.is_active)
          OR NOT EXISTS (SELECT 1 FROM chunk_embeddings e WHERE e.embedding_run_id = NEW.id)
        THEN RAISE EXCEPTION 'An active embedding run requires a current dataset and vectors';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER m4_run_guard BEFORE INSERT OR UPDATE ON embedding_runs
      FOR EACH ROW EXECUTE FUNCTION m4_run_guard();

    CREATE FUNCTION m4_index_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'STAGING' OR NEW.is_active
        THEN RAISE EXCEPTION 'Index runs must begin staging and inactive'; END IF;
        RETURN NEW;
      END IF;
      IF ROW(NEW.tenant_id, NEW.document_id, NEW.document_version_id, NEW.embedding_run_id,
             NEW.embedding_version_id, NEW.physical_collection, NEW.vector_name,
             NEW.schema_version, NEW.attempt)
         IS DISTINCT FROM ROW(OLD.tenant_id, OLD.document_id, OLD.document_version_id,
             OLD.embedding_run_id, OLD.embedding_version_id, OLD.physical_collection,
             OLD.vector_name, OLD.schema_version, OLD.attempt)
      THEN RAISE EXCEPTION 'Index run identity is immutable'; END IF;
      -- Only a fully reconciled run may become active, and only alongside its own embedding run.
      IF NEW.is_active AND NOT OLD.is_active THEN
        IF NEW.status <> 'VERIFIED'
          OR NEW.verified_point_count <> NEW.expected_point_count
          OR NOT EXISTS (SELECT 1 FROM embedding_runs r
               WHERE r.id = NEW.embedding_run_id AND r.status = 'SUCCEEDED'
                 AND r.failed_chunk_count = 0)
        THEN RAISE EXCEPTION 'Only a verified, complete index run can be activated'; END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER m4_index_guard BEFORE INSERT OR UPDATE ON index_runs
      FOR EACH ROW EXECUTE FUNCTION m4_index_guard();

    CREATE FUNCTION m4_record_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE owner_status text; owner_id uuid;
    BEGIN
      owner_id = CASE WHEN TG_OP = 'DELETE' THEN OLD.embedding_run_id ELSE NEW.embedding_run_id END;
      IF owner_id IS NULL THEN RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END IF;
      SELECT status INTO owner_status FROM embedding_runs WHERE id = owner_id;
      IF owner_status IS DISTINCT FROM 'RUNNING'
      THEN RAISE EXCEPTION 'Completed embedding datasets cannot be changed'; END IF;
      IF TG_TABLE_NAME = 'chunk_embeddings' AND TG_OP <> 'DELETE' THEN
        -- The vector must describe a chunk of the run's own dataset, in the run's own tenant.
        IF NOT EXISTS (SELECT 1 FROM chunks c JOIN embedding_runs r ON r.id = NEW.embedding_run_id
          WHERE c.id = NEW.chunk_id AND c.chunk_run_id = r.chunk_run_id
            AND c.tenant_id = r.tenant_id AND NEW.tenant_id = r.tenant_id)
        THEN RAISE EXCEPTION 'Embedding source chunk scope invalid'; END IF;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER m4_record_guard BEFORE INSERT OR UPDATE OR DELETE ON chunk_embeddings
      FOR EACH ROW EXECUTE FUNCTION m4_record_guard();

    CREATE FUNCTION m4_invalidate_index() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      -- A superseded chunk dataset invalidates every index built from it, so a stale index can
      -- never remain the active corpus for a version that was rechunked or reparsed.
      IF OLD.is_active AND NOT NEW.is_active THEN
        UPDATE index_runs SET is_active = false, status = 'SUPERSEDED'
          WHERE chunk_run_id = NEW.id AND is_active;
        UPDATE embedding_runs SET is_active = false WHERE chunk_run_id = NEW.id AND is_active;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER m4_chunks_superseded AFTER UPDATE OF is_active ON chunk_runs
      FOR EACH ROW EXECUTE FUNCTION m4_invalidate_index();
    """)
    # Findings are an append-only audit of what validation observed.
    op.execute("""
    CREATE TRIGGER index_findings_append_only BEFORE UPDATE OR DELETE
      ON index_validation_findings FOR EACH ROW EXECUTE FUNCTION m1_append_only();
    """)
