"""m5 hybrid retrieval: lexical index, query encoder identity and the retrieval-ready state

Adds the durable lexical (BM25) index beside the M4 dense index, the query-encoder version record,
and three ingestion states. Widening the status column is the one structural change to an existing
table: see `_rewrite_status_columns` for why that requires dropping and recreating an M3 trigger.

The downgrade refuses to run while any job still holds an M5 state, and restores the M4 transition
guard exactly rather than approximating it.

Revision ID: m5_hybrid_retrieval
Revises: m4_embeddings_and_index
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'm5_hybrid_retrieval'
down_revision = 'm4_embeddings_and_index'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_encoder_versions',
    sa.Column('model_provider', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('model_revision', sa.String(length=80), nullable=False),
    sa.Column('tokenizer_revision', sa.String(length=80), nullable=False),
    sa.Column('model_checksum', sa.String(length=64), nullable=False),
    sa.Column('tokenizer_checksum', sa.String(length=64), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('pooling_strategy', sa.String(length=24), nullable=False),
    sa.Column('normalization', sa.String(length=24), nullable=False),
    sa.Column('distance_metric', sa.String(length=16), nullable=False),
    sa.Column('max_query_tokens', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(length=16), nullable=False),
    sa.Column('normalization_version', sa.String(length=80), nullable=False),
    sa.Column('configuration_version', sa.String(length=80), nullable=False),
    sa.Column('semantics_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('policy_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('library_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("distance_metric IN ('DOT','COSINE','EUCLID')", name=op.f('ck_query_encoder_versions_query_encoder_distance_metric')),
    sa.CheckConstraint('embedding_dimension > 0', name=op.f('ck_query_encoder_versions_query_encoder_dimension_positive')),
    sa.CheckConstraint('max_query_tokens > 0', name=op.f('ck_query_encoder_versions_query_encoder_max_tokens_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_encoder_versions')),
    sa.UniqueConstraint('semantics_fingerprint', name='uq_query_encoder_versions_semantics')
    )
    op.create_index(op.f('ix_query_encoder_versions_model_id'), 'query_encoder_versions', ['model_id'], unique=False)
    op.create_table('sparse_index_versions',
    sa.Column('analyzer_name', sa.String(length=80), nullable=False),
    sa.Column('analyzer_version', sa.String(length=40), nullable=False),
    sa.Column('unicode_normalization', sa.String(length=16), nullable=False),
    sa.Column('case_policy', sa.String(length=30), nullable=False),
    sa.Column('compound_policy', sa.String(length=30), nullable=False),
    sa.Column('stopword_policy', sa.String(length=30), nullable=False),
    sa.Column('stopword_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_term_length', sa.Integer(), nullable=False),
    sa.Column('max_term_length', sa.Integer(), nullable=False),
    sa.Column('expansion', sa.String(length=20), nullable=False),
    sa.Column('configuration_version', sa.String(length=80), nullable=False),
    sa.Column('analyzer_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('policy_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("case_policy IN ('NORMALIZED','NORMALIZED_AND_EXACT')", name=op.f('ck_sparse_index_versions_sparse_case_policy')),
    sa.CheckConstraint("compound_policy IN ('WHOLE','WHOLE_AND_PARTS')", name=op.f('ck_sparse_index_versions_sparse_compound_policy')),
    sa.CheckConstraint("expansion = 'NONE'", name=op.f('ck_sparse_index_versions_sparse_no_uncontrolled_expansion')),
    sa.CheckConstraint('min_term_length >= 1 AND max_term_length >= min_term_length', name=op.f('ck_sparse_index_versions_sparse_term_length_bounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sparse_index_versions')),
    sa.UniqueConstraint('analyzer_fingerprint', name='uq_sparse_index_versions_analyzer')
    )
    op.create_index(op.f('ix_sparse_index_versions_analyzer_name'), 'sparse_index_versions', ['analyzer_name'], unique=False)
    op.create_table('sparse_indexes',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_run_id', sa.Uuid(), nullable=False),
    sa.Column('sparse_index_version_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_job_id', sa.Uuid(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expected_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('indexed_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('term_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('posting_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_length', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('corpus_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('policy_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('worker_identity', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT is_active OR (status = 'VERIFIED' AND verified_chunk_count = expected_chunk_count AND indexed_chunk_count = expected_chunk_count)", name=op.f('ck_sparse_indexes_active_sparse_index_verified')),
    sa.CheckConstraint("status IN ('STAGING','VERIFYING','VERIFIED','FAILED','CANCELLED','SUPERSEDED')", name=op.f('ck_sparse_indexes_sparse_index_status')),
    sa.CheckConstraint('expected_chunk_count >= 0 AND indexed_chunk_count >= 0 AND verified_chunk_count >= 0 AND posting_count >= 0 AND term_count >= 0 AND total_length >= 0', name=op.f('ck_sparse_indexes_sparse_counts_nonnegative')),
    sa.ForeignKeyConstraint(['chunk_run_id', 'document_version_id', 'tenant_id'], ['chunk_runs.id', 'chunk_runs.document_version_id', 'chunk_runs.tenant_id'], name=op.f('fk_sparse_indexes_chunk_run_id_chunk_runs')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_sparse_indexes_document_id_documents')),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], name=op.f('fk_sparse_indexes_ingestion_job_id_ingestion_jobs')),
    sa.ForeignKeyConstraint(['sparse_index_version_id'], ['sparse_index_versions.id'], name=op.f('fk_sparse_indexes_sparse_index_version_id_sparse_index_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sparse_indexes')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_sparse_indexes_id_tenant'),
    sa.UniqueConstraint('ingestion_job_id', 'generation', name='uq_sparse_indexes_job_generation')
    )
    op.create_index(op.f('ix_sparse_indexes_chunk_run_id'), 'sparse_indexes', ['chunk_run_id'], unique=False)
    op.create_index(op.f('ix_sparse_indexes_document_version_id'), 'sparse_indexes', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_sparse_indexes_ingestion_job_id'), 'sparse_indexes', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_sparse_indexes_lease_expires_at'), 'sparse_indexes', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_sparse_indexes_sparse_index_version_id'), 'sparse_indexes', ['sparse_index_version_id'], unique=False)
    op.create_index(op.f('ix_sparse_indexes_status'), 'sparse_indexes', ['status'], unique=False)
    op.create_index(op.f('ix_sparse_indexes_tenant_id'), 'sparse_indexes', ['tenant_id'], unique=False)
    op.create_index('uq_sparse_index_active_version', 'sparse_indexes', ['document_version_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('uq_sparse_index_pending_version', 'sparse_indexes', ['document_version_id'], unique=True, postgresql_where=sa.text("status IN ('STAGING','VERIFYING')"))
    op.create_table('sparse_postings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sparse_index_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=80), nullable=False),
    sa.Column('term_frequency', sa.Integer(), nullable=False),
    sa.CheckConstraint('term_frequency > 0', name=op.f('ck_sparse_postings_sparse_posting_frequency_positive')),
    sa.ForeignKeyConstraint(['sparse_index_id'], ['sparse_indexes.id'], name=op.f('fk_sparse_postings_sparse_index_id_sparse_indexes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sparse_postings')),
    sa.UniqueConstraint('sparse_index_id', 'chunk_id', 'term', name='uq_sparse_postings_identity')
    )
    op.create_index(op.f('ix_sparse_postings_sparse_index_id'), 'sparse_postings', ['sparse_index_id'], unique=False)
    op.create_index('ix_sparse_postings_term', 'sparse_postings', ['term', 'sparse_index_id'], unique=False)
    op.create_table('sparse_terms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sparse_index_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=80), nullable=False),
    sa.Column('document_frequency', sa.Integer(), nullable=False),
    sa.Column('total_frequency', sa.Integer(), nullable=False),
    sa.CheckConstraint('document_frequency > 0 AND total_frequency >= document_frequency', name=op.f('ck_sparse_terms_sparse_term_frequencies_positive')),
    sa.ForeignKeyConstraint(['sparse_index_id'], ['sparse_indexes.id'], name=op.f('fk_sparse_terms_sparse_index_id_sparse_indexes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sparse_terms')),
    sa.UniqueConstraint('sparse_index_id', 'term', name='uq_sparse_terms_identity')
    )
    op.create_index(op.f('ix_sparse_terms_sparse_index_id'), 'sparse_terms', ['sparse_index_id'], unique=False)
    op.create_index('ix_sparse_terms_term', 'sparse_terms', ['term', 'sparse_index_id'], unique=False)
    op.create_table('sparse_validation_findings',
    sa.Column('sparse_index_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','WARNING','ERROR','CRITICAL')", name=op.f('ck_sparse_validation_findings_sparse_finding_severity')),
    sa.ForeignKeyConstraint(['sparse_index_id'], ['sparse_indexes.id'], name=op.f('fk_sparse_validation_findings_sparse_index_id_sparse_indexes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sparse_validation_findings'))
    )
    op.create_index(op.f('ix_sparse_validation_findings_code'), 'sparse_validation_findings', ['code'], unique=False)
    op.create_index(op.f('ix_sparse_validation_findings_sparse_index_id'), 'sparse_validation_findings', ['sparse_index_id'], unique=False)
    op.create_table('sparse_documents',
    sa.Column('sparse_index_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_type', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('authority_level', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('distinct_terms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length >= 0 AND distinct_terms >= 0', name=op.f('ck_sparse_documents_sparse_document_lengths')),
    sa.ForeignKeyConstraint(['chunk_id', 'chunk_run_id'], ['chunks.id', 'chunks.chunk_run_id'], name=op.f('fk_sparse_documents_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['sparse_index_id', 'tenant_id'], ['sparse_indexes.id', 'sparse_indexes.tenant_id'], name=op.f('fk_sparse_documents_sparse_index_id_sparse_indexes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sparse_documents')),
    sa.UniqueConstraint('sparse_index_id', 'chunk_id', name='uq_sparse_documents_index_chunk')
    )
    op.create_index(op.f('ix_sparse_documents_chunk_id'), 'sparse_documents', ['chunk_id'], unique=False)
    op.create_index('ix_sparse_documents_scope', 'sparse_documents', ['sparse_index_id', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_sparse_documents_sparse_index_id'), 'sparse_documents', ['sparse_index_id'], unique=False)
    op.create_index(op.f('ix_sparse_documents_tenant_id'), 'sparse_documents', ['tenant_id'], unique=False)
    _widen_status_columns()
    op.add_column('outbox_messages', sa.Column('sparse_index_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_outbox_messages_sparse_index_id_sparse_indexes'), 'outbox_messages', 'sparse_indexes', ['sparse_index_id'], ['id'])
    # ### end Alembic commands ###
    _install_guards()

def downgrade() -> None:
    _prepare_downgrade()
    _restore_m4()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_outbox_messages_sparse_index_id_sparse_indexes'), 'outbox_messages', type_='foreignkey')
    op.drop_column('outbox_messages', 'sparse_index_id')
    _narrow_status_columns()
    op.drop_index(op.f('ix_sparse_documents_tenant_id'), table_name='sparse_documents')
    op.drop_index(op.f('ix_sparse_documents_sparse_index_id'), table_name='sparse_documents')
    op.drop_index('ix_sparse_documents_scope', table_name='sparse_documents')
    op.drop_index(op.f('ix_sparse_documents_chunk_id'), table_name='sparse_documents')
    op.drop_table('sparse_documents')
    op.drop_index(op.f('ix_sparse_validation_findings_sparse_index_id'), table_name='sparse_validation_findings')
    op.drop_index(op.f('ix_sparse_validation_findings_code'), table_name='sparse_validation_findings')
    op.drop_table('sparse_validation_findings')
    op.drop_index('ix_sparse_terms_term', table_name='sparse_terms')
    op.drop_index(op.f('ix_sparse_terms_sparse_index_id'), table_name='sparse_terms')
    op.drop_table('sparse_terms')
    op.drop_index('ix_sparse_postings_term', table_name='sparse_postings')
    op.drop_index(op.f('ix_sparse_postings_sparse_index_id'), table_name='sparse_postings')
    op.drop_table('sparse_postings')
    op.drop_index('uq_sparse_index_pending_version', table_name='sparse_indexes', postgresql_where=sa.text("status IN ('STAGING','VERIFYING')"))
    op.drop_index('uq_sparse_index_active_version', table_name='sparse_indexes', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_sparse_indexes_tenant_id'), table_name='sparse_indexes')
    op.drop_index(op.f('ix_sparse_indexes_status'), table_name='sparse_indexes')
    op.drop_index(op.f('ix_sparse_indexes_sparse_index_version_id'), table_name='sparse_indexes')
    op.drop_index(op.f('ix_sparse_indexes_lease_expires_at'), table_name='sparse_indexes')
    op.drop_index(op.f('ix_sparse_indexes_ingestion_job_id'), table_name='sparse_indexes')
    op.drop_index(op.f('ix_sparse_indexes_document_version_id'), table_name='sparse_indexes')
    op.drop_index(op.f('ix_sparse_indexes_chunk_run_id'), table_name='sparse_indexes')
    op.drop_table('sparse_indexes')
    op.drop_index(op.f('ix_sparse_index_versions_analyzer_name'), table_name='sparse_index_versions')
    op.drop_table('sparse_index_versions')
    op.drop_index(op.f('ix_query_encoder_versions_model_id'), table_name='query_encoder_versions')
    op.drop_table('query_encoder_versions')
    # ### end Alembic commands ###


# ---------------------------------------------------------------------------- status vocabulary

# VERIFYING_SPARSE_INDEX is 22 characters, three more than the widest status M4 needed, so unlike
# M4 this revision genuinely has to widen the column. That is only possible after dropping the M3
# trigger declared as `AFTER UPDATE OF status`: PostgreSQL refuses to alter the type of a column
# named in a trigger definition. The trigger is recreated immediately afterwards and the function
# it calls is untouched, so the invalidation behaviour it implements is unchanged.
#
# The alternative was to abbreviate the state names until they fitted. Precision in a state that
# operators read and reason about is worth one careful column change.
M5_STATUS_ADDITIONS = ("RETRIEVAL_READY", "SPARSE_INDEXING", "VERIFYING_SPARSE_INDEX")
M5_WIDTH = 22
M4_WIDTH = 19

JOB_CANCELLED_TRIGGER = (
    "CREATE TRIGGER m3_job_cancelled AFTER UPDATE OF status ON ingestion_jobs "
    "FOR EACH ROW EXECUTE FUNCTION m3_invalidate_chunks()"
)


def _m4_status_set() -> tuple[str, ...]:
    from migrations.versions.m4_embeddings_and_index_m4_embeddings_and_vector_index import (
        M4_STATUS_ADDITIONS,
        _m3_status_set,
    )

    return _m3_status_set() + M4_STATUS_ADDITIONS


def _rewrite_status_columns(values: tuple[str, ...], width: int, previous: int) -> None:
    from migrations.versions.m2_document_parsing import STATUS_CONSTRAINTS

    listed = ", ".join(f"'{value}'" for value in values)
    op.execute("DROP TRIGGER IF EXISTS m3_job_cancelled ON ingestion_jobs")
    for table, column, name in STATUS_CONSTRAINTS:
        op.execute('ALTER TABLE ' + table + ' DROP CONSTRAINT IF EXISTS "ck_' + table + '_' + name + '"')
        op.alter_column(
            table,
            column,
            type_=sa.String(length=width),
            existing_type=sa.String(length=previous),
            existing_nullable=False,
        )
        op.execute(
            'ALTER TABLE ' + table + ' ADD CONSTRAINT "ck_' + table + '_' + name + '" '
            "CHECK (" + column + " IN (" + listed + "))"
        )
    op.execute(JOB_CANCELLED_TRIGGER)


def _widen_status_columns() -> None:
    _rewrite_status_columns(_m4_status_set() + M5_STATUS_ADDITIONS, M5_WIDTH, M4_WIDTH)


def _narrow_status_columns() -> None:
    _rewrite_status_columns(_m4_status_set(), M4_WIDTH, M5_WIDTH)


def _prepare_downgrade() -> None:
    """Refuse to erase live M5 state.

    A job or version still holding one of the M5 statuses cannot be represented once this revision
    is removed. Rather than silently rewriting it to something else, the downgrade stops and names
    the action an operator must take. Nothing is ever quietly reinterpreted.
    """
    op.execute("DELETE FROM outbox_messages WHERE kind = 'SPARSE_INDEX'")
    listed = ", ".join("'" + value + "'" for value in M5_STATUS_ADDITIONS)
    op.execute(
        "DO $$ DECLARE remaining bigint; BEGIN "
        "SELECT (SELECT count(*) FROM ingestion_jobs WHERE status IN (" + listed + ")) "
        "+ (SELECT count(*) FROM document_versions WHERE ingestion_status IN (" + listed + ")) "
        "INTO remaining; "
        "IF remaining > 0 THEN RAISE EXCEPTION "
        "'Cancel the % job(s) still in an M5 state before downgrading', remaining; END IF; "
        "END $$;"
    )


# ------------------------------------------------------------------------------------ job guard

# The M4 graph plus the lexical stages and the lexical-only rebuild edge. READY is still absent
# from every right-hand side, and deliberately so: READY would mean the corpus is answerable, and
# nothing in M5 makes it answerable. Reaching RETRIEVAL_READY means both retrieval lanes verified
# on one chunk dataset — evidence can be found, not that an answer may be produced from it.
M5_JOB_GUARD = """
    CREATE OR REPLACE FUNCTION m1_job_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'UPLOADED' OR NEW.retry_count <> 0
        THEN RAISE EXCEPTION 'Jobs must begin UPLOADED'; END IF;
        RETURN NEW;
      END IF;
      IF ROW(NEW.document_version_id, NEW.tenant_id, NEW.requested_by_user_id,
             NEW.configuration_version, NEW.config_snapshot, NEW.max_retries)
         IS DISTINCT FROM ROW(OLD.document_version_id, OLD.tenant_id, OLD.requested_by_user_id,
             OLD.configuration_version, OLD.config_snapshot, OLD.max_retries)
      THEN RAISE EXCEPTION 'Job provenance and configuration are immutable'; END IF;
      IF NEW.status IS DISTINCT FROM OLD.status THEN
        IF NOT (
          (OLD.status = 'UPLOADED' AND NEW.status IN ('VALIDATING', 'CANCELLED')) OR
          (OLD.status = 'VALIDATING' AND NEW.status IN
            ('QUEUED', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'QUEUED' AND NEW.status IN
            ('PARSING', 'FAILED', 'QUARANTINED', 'CANCELLED')) OR
          (OLD.status = 'PARSING' AND NEW.status IN
            ('NORMALIZING', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'NORMALIZING' AND NEW.status IN
            ('ENRICHING', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'ENRICHING' AND NEW.status IN
            ('READY_FOR_CHUNKING', 'FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'CANCELLED')) OR
          (OLD.status = 'READY_FOR_CHUNKING' AND NEW.status IN
            ('CHUNKING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'CHUNKING' AND NEW.status IN
            ('VALIDATING_CHUNKS','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'VALIDATING_CHUNKS' AND NEW.status IN
            ('READY_FOR_EMBEDDING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'READY_FOR_EMBEDDING' AND NEW.status IN
            ('EMBEDDING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'EMBEDDING' AND NEW.status IN
            ('INDEXING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'INDEXING' AND NEW.status IN
            ('VERIFYING_INDEX','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'VERIFYING_INDEX' AND NEW.status IN
            ('READY_FOR_RETRIEVAL','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'READY_FOR_RETRIEVAL' AND NEW.status IN
            ('SPARSE_INDEXING','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'SPARSE_INDEXING' AND NEW.status IN
            ('VERIFYING_SPARSE_INDEX','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status = 'VERIFYING_SPARSE_INDEX' AND NEW.status IN
            ('RETRIEVAL_READY','FAILED','QUARANTINED','NEEDS_REVIEW','CANCELLED')) OR
          (OLD.status IN ('FAILED', 'QUARANTINED', 'NEEDS_REVIEW', 'READY_FOR_CHUNKING',
                          'READY_FOR_EMBEDDING', 'READY_FOR_RETRIEVAL', 'RETRIEVAL_READY')
           AND NEW.status = 'CANCELLED') OR
          -- Retry, reparse, rechunk, re-embed and lexical rebuild all consume one unit of the
          -- same bounded budget, so no reprocessing path can loop without limit.
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_CHUNKING', 'READY_FOR_EMBEDDING',
                          'READY_FOR_RETRIEVAL', 'RETRIEVAL_READY')
           AND NEW.status = 'VALIDATING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries) OR
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_EMBEDDING', 'READY_FOR_RETRIEVAL',
                          'RETRIEVAL_READY')
           AND NEW.status = 'READY_FOR_CHUNKING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries) OR
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_RETRIEVAL', 'RETRIEVAL_READY')
           AND NEW.status = 'READY_FOR_EMBEDDING'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries) OR
          (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'RETRIEVAL_READY')
           AND NEW.status = 'READY_FOR_RETRIEVAL'
           AND NEW.retry_count = OLD.retry_count + 1 AND NEW.retry_count <= NEW.max_retries))
        THEN RAISE EXCEPTION 'Illegal ingestion transition'; END IF;
      END IF;
      IF NEW.retry_count <> OLD.retry_count AND NOT
        (OLD.status IN ('FAILED', 'NEEDS_REVIEW', 'READY_FOR_CHUNKING', 'READY_FOR_EMBEDDING',
                        'READY_FOR_RETRIEVAL', 'RETRIEVAL_READY')
         AND NEW.status IN ('VALIDATING','READY_FOR_CHUNKING','READY_FOR_EMBEDDING',
                            'READY_FOR_RETRIEVAL')
         AND NEW.retry_count = OLD.retry_count + 1)
      THEN RAISE EXCEPTION
        'Retry count can change only on a retry, reparse, rechunk, re-embed or lexical rebuild';
      END IF;
      RETURN NEW;
    END $$;
    """

SPARSE_GUARDS = """
    CREATE FUNCTION m5_sparse_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'STAGING' OR NEW.is_active OR NEW.activated_at IS NOT NULL
        THEN RAISE EXCEPTION 'Lexical indexes must begin staging and inactive'; END IF;
        RETURN NEW;
      END IF;
      IF ROW(NEW.tenant_id, NEW.document_id, NEW.document_version_id, NEW.chunk_run_id,
             NEW.sparse_index_version_id, NEW.ingestion_job_id, NEW.generation,
             NEW.schema_version)
         IS DISTINCT FROM ROW(OLD.tenant_id, OLD.document_id, OLD.document_version_id,
             OLD.chunk_run_id, OLD.sparse_index_version_id, OLD.ingestion_job_id, OLD.generation,
             OLD.schema_version)
      THEN RAISE EXCEPTION 'Lexical index identity is immutable'; END IF;
      IF NEW.activated_at IS DISTINCT FROM OLD.activated_at AND OLD.activated_at IS NOT NULL
      THEN RAISE EXCEPTION 'Lexical index activation time is written once'; END IF;
      IF OLD.status NOT IN ('STAGING','VERIFYING') THEN
        -- A finished index is a historical record. Only its activation state may still move,
        -- and the activation timestamp may only be written once.
        IF (to_jsonb(NEW) - 'is_active' - 'status' - 'activated_at' - 'updated_at')
           IS DISTINCT FROM (to_jsonb(OLD) - 'is_active' - 'status' - 'activated_at' - 'updated_at')
        THEN RAISE EXCEPTION 'Completed lexical indexes are immutable'; END IF;
        IF NEW.activated_at IS DISTINCT FROM OLD.activated_at AND OLD.activated_at IS NOT NULL
        THEN RAISE EXCEPTION 'Lexical index activation time is written once'; END IF;
        IF NEW.status IS DISTINCT FROM OLD.status
           AND NOT (OLD.status = 'VERIFIED' AND NEW.status = 'SUPERSEDED')
        THEN RAISE EXCEPTION 'Completed lexical indexes are immutable'; END IF;
      END IF;
      -- Only a fully reconciled index may become active, and only on the same chunk dataset the
      -- active dense index was built from. This is the database-level form of the rule the
      -- retrieval service relies on when it fuses the two lanes.
      IF NEW.is_active AND NOT OLD.is_active THEN
        IF NEW.status <> 'VERIFIED' OR NEW.activated_at IS NULL
          OR NEW.verified_chunk_count <> NEW.expected_chunk_count
          OR NEW.indexed_chunk_count <> NEW.expected_chunk_count
          OR NOT EXISTS (SELECT 1 FROM chunk_runs c
               WHERE c.id = NEW.chunk_run_id AND c.is_active)
          OR NOT EXISTS (SELECT 1 FROM index_runs r
               WHERE r.document_version_id = NEW.document_version_id AND r.is_active
                 AND r.status = 'VERIFIED' AND r.chunk_run_id = NEW.chunk_run_id)
        THEN RAISE EXCEPTION
          'Only a verified lexical index on the active dense chunk dataset can be activated';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER m5_sparse_guard BEFORE INSERT OR UPDATE ON sparse_indexes
      FOR EACH ROW EXECUTE FUNCTION m5_sparse_guard();

    CREATE FUNCTION m5_sparse_record_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE owner_status text; owner_id uuid;
    BEGIN
      owner_id = CASE WHEN TG_OP = 'DELETE' THEN OLD.sparse_index_id ELSE NEW.sparse_index_id END;
      IF owner_id IS NULL THEN RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END IF;
      SELECT status INTO owner_status FROM sparse_indexes WHERE id = owner_id;
      IF owner_status IS DISTINCT FROM 'STAGING'
      THEN RAISE EXCEPTION 'Completed lexical indexes cannot be changed'; END IF;
      IF TG_TABLE_NAME = 'sparse_documents' AND TG_OP <> 'DELETE' THEN
        -- The row must describe a chunk of the index's own dataset, in the index's own tenant.
        IF NOT EXISTS (SELECT 1 FROM chunks c JOIN sparse_indexes s ON s.id = NEW.sparse_index_id
          WHERE c.id = NEW.chunk_id AND c.chunk_run_id = s.chunk_run_id
            AND c.tenant_id = s.tenant_id AND NEW.tenant_id = s.tenant_id)
        THEN RAISE EXCEPTION 'Lexical source chunk scope invalid'; END IF;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$;

    CREATE FUNCTION m5_invalidate_sparse() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      -- A superseded chunk dataset invalidates the lexical index built from it, exactly as it
      -- already invalidates the dense one. Leaving a stale lexical index active would let a
      -- hybrid query fuse candidates from two different versions of the same document.
      IF OLD.is_active AND NOT NEW.is_active THEN
        UPDATE sparse_indexes SET is_active = false, status = 'SUPERSEDED'
          WHERE chunk_run_id = NEW.id AND is_active;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER m5_chunks_superseded_sparse AFTER UPDATE OF is_active ON chunk_runs
      FOR EACH ROW EXECUTE FUNCTION m5_invalidate_sparse();
    """

RECORD_TABLES = ("sparse_documents", "sparse_postings", "sparse_terms")


def _install_guards() -> None:
    op.execute(M5_JOB_GUARD)
    op.execute(SPARSE_GUARDS)
    for table in RECORD_TABLES:
        op.execute(
            "CREATE TRIGGER m5_sparse_record_guard BEFORE INSERT OR UPDATE OR DELETE ON "
            + table
            + " FOR EACH ROW EXECUTE FUNCTION m5_sparse_record_guard()"
        )
    # Findings are an append-only audit of what verification observed.
    op.execute(
        "CREATE TRIGGER sparse_findings_append_only BEFORE UPDATE OR DELETE "
        "ON sparse_validation_findings FOR EACH ROW EXECUTE FUNCTION m1_append_only()"
    )


def _restore_m4() -> None:
    from migrations.versions.m4_embeddings_and_index_m4_embeddings_and_vector_index import (
        M4_JOB_GUARD,
    )

    op.execute("DROP TRIGGER IF EXISTS m5_sparse_guard ON sparse_indexes")
    for table in RECORD_TABLES:
        op.execute("DROP TRIGGER IF EXISTS m5_sparse_record_guard ON " + table)
    op.execute(
        "DROP TRIGGER IF EXISTS sparse_findings_append_only ON sparse_validation_findings"
    )
    op.execute("DROP TRIGGER IF EXISTS m5_chunks_superseded_sparse ON chunk_runs")
    op.execute("DROP FUNCTION IF EXISTS m5_sparse_guard()")
    op.execute("DROP FUNCTION IF EXISTS m5_sparse_record_guard()")
    op.execute("DROP FUNCTION IF EXISTS m5_invalidate_sparse()")
    op.execute(M4_JOB_GUARD)
