"""m9 conversations: durable Ask history, tenant-scoped, with the answer rule in the schema

The first new durable state since M1. A conversation the user returns to must outlive the request
that produced it, so questions, outcomes and the sources behind a verified answer are stored. What
is deliberately absent is as important: no prompt, no provider response, no draft that failed
verification, no verifier reasoning and no request-scoped EvidenceSet.

Two CHECK constraints put the milestone's safety rule in the database rather than only in
application code: `answer_text` exists if and only if the outcome is VERIFIED, and `verified`
agrees with the outcome. An unverified draft cannot be written into the column a verified answer is
read from, whatever a future caller does.

The downgrade refuses while conversations still exist. Every other table in this system can be
rebuilt from its source document; a user's question history cannot, and dropping it silently to
move a schema pointer would be the one irreversible thing a migration in this repository does.

Revision ID: m9_conversations
Revises: m5_hybrid_retrieval
"""
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'm9_conversations'
down_revision = 'm5_hybrid_retrieval'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id', 'tenant_id'], ['users.id', 'users.tenant_id'], name=op.f('fk_conversations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_conversations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('id', 'tenant_id', name=op.f('uq_conversations_id'))
    )
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sufficiency_status', sa.String(length=24), nullable=True),
    sa.Column('verification_outcome', sa.String(length=24), nullable=True),
    sa.Column('repair_count', sa.Integer(), nullable=False),
    sa.Column('generator_model', sa.String(length=200), nullable=True),
    sa.Column('verifier_model', sa.String(length=200), nullable=True),
    sa.Column('verifier_independent', sa.Boolean(), nullable=True),
    sa.Column('durations_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(outcome = 'VERIFIED') = (answer_text IS NOT NULL)", name=op.f('ck_conversation_turns_answer_only_when_verified')),
    sa.CheckConstraint("(outcome = 'VERIFIED') = verified", name=op.f('ck_conversation_turns_verified_matches_outcome')),
    sa.CheckConstraint("outcome IN ('VERIFIED', 'INSUFFICIENT_EVIDENCE', 'CONFLICTING_EVIDENCE', 'UNVERIFIED', 'FAILED')", name=op.f('ck_conversation_turns_turn_outcome')),
    sa.CheckConstraint('repair_count >= 0 AND repair_count <= 1', name=op.f('ck_conversation_turns_bounded_repair')),
    sa.ForeignKeyConstraint(['conversation_id', 'tenant_id'], ['conversations.id', 'conversations.tenant_id'], name=op.f('fk_conversation_turns_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['created_by_user_id', 'tenant_id'], ['users.id', 'users.tenant_id'], name=op.f('fk_conversation_turns_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_conversation_turns_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns')),
    sa.UniqueConstraint('conversation_id', 'sequence_number', name='uq_turn_sequence'),
    sa.UniqueConstraint('id', 'tenant_id', name=op.f('uq_conversation_turns_id')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_turn_idempotency')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_tenant_id'), 'conversation_turns', ['tenant_id'], unique=False)
    op.create_table('turn_citations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_run_id', sa.Uuid(), nullable=False),
    sa.Column('parse_run_id', sa.Uuid(), nullable=False),
    sa.Column('document_title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('authority_level', sa.String(length=30), nullable=False),
    sa.Column('chunk_type', sa.String(length=40), nullable=False),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_element_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cited_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id', 'tenant_id'], ['documents.id', 'documents.tenant_id'], name=op.f('fk_turn_citations_document_id_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_turn_citations_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['turn_id', 'tenant_id'], ['conversation_turns.id', 'conversation_turns.tenant_id'], name=op.f('fk_turn_citations_turn_id_conversation_turns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turn_citations')),
    sa.UniqueConstraint('id', 'tenant_id', name=op.f('uq_turn_citations_id')),
    sa.UniqueConstraint('turn_id', 'evidence_id', name='uq_citation_evidence')
    )
    op.create_index(op.f('ix_turn_citations_tenant_id'), 'turn_citations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_turn_citations_turn_id'), 'turn_citations', ['turn_id'], unique=False)
    # ### end Alembic commands ###

def _refuse_if_history_exists() -> None:
    """Stop rather than delete a user's question history.

    `MEDRAG_ALLOW_CONVERSATION_LOSS=1` acknowledges the loss deliberately. It exists for throwaway
    schemas — the integration harness proves every migration is reversible on a schema it created
    seconds earlier — and makes the destructive path something an operator has to opt into rather
    than something they discover afterwards.
    """
    if os.environ.get("MEDRAG_ALLOW_CONVERSATION_LOSS") == "1":
        return
    bind = op.get_bind()
    existing = bind.execute(sa.text("SELECT count(*) FROM conversations")).scalar() or 0
    if existing:
        raise RuntimeError(
            f"{existing} conversation(s) still exist. Downgrading would delete user question "
            "history permanently. Export them first, or set MEDRAG_ALLOW_CONVERSATION_LOSS=1 to "
            "acknowledge the loss."
        )


def downgrade() -> None:
    _refuse_if_history_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_citations_turn_id'), table_name='turn_citations')
    op.drop_index(op.f('ix_turn_citations_tenant_id'), table_name='turn_citations')
    op.drop_table('turn_citations')
    op.drop_index(op.f('ix_conversation_turns_tenant_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
