import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';

test('authorized PDF upload reaches QUEUED, worker receipt and visible provenance', async ({ page }, testInfo) => {
  test.setTimeout(90000);
  test.skip(process.env.MEDRAG_E2E_LIVE !== '1', 'Requires the running M1 API, worker and dispatcher.');
  const credentials = JSON.parse(process.env.MEDRAG_DEV_PRINCIPALS ?? '[]') as { token: string; role: string }[];
  const token = credentials.find(item => item.role === 'admin')?.token;
  if (!token) throw new Error('Provision development credentials and pass the environment to Playwright.');
  const title = 'Browser fixture ' + randomUUID().slice(0, 8);
  const buffer = Buffer.concat([readFileSync(resolve('../backend/tests/fixtures/valid.pdf')), Buffer.from('\n% ' + randomUUID() + '\n')]);
  await page.goto('/library');
  await page.getByLabel('Access key').fill(token);
  await page.getByRole('button', { name: 'Open workspace' }).click();
  await page.getByLabel('Title', { exact: true }).fill(title);
  await page.getByRole('combobox', { name: 'Source type', exact: true }).selectOption('TEXTBOOK');
  await page.getByRole('combobox', { name: 'Authority level', exact: true }).selectOption('UNREVIEWED');
  await page.getByLabel('Edition', { exact: true }).fill('Synthetic first edition');
  await page.getByLabel('Choose PDF files or drag them here').setInputFiles({ name: 'browser-fixture.pdf', mimeType: 'application/pdf', buffer });
  await page.getByRole('button', { name: 'Upload documents' }).click();
  await expect(page.getByRole('status')).toContainText('Upload recorded', { timeout: 30000 });
  await expect(page.locator('.success-list').getByText('queued', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: title, exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('library-desktop.png'), fullPage: true });
  await page.getByRole('link', { name: 'Open uploaded document' }).click();
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
  await expect(page.getByText(/SHA-256:/)).toBeVisible();
  await page.getByRole('button', { name: 'Inspect history' }).click();
  const history = page.locator('.history');
  await expect(history.getByText('uploaded', { exact: true })).toBeVisible();
  await expect(history.getByText('validating', { exact: true })).toBeVisible();
  await expect(history.getByText('queued', { exact: true })).toBeVisible();
  await expect(history.getByText(/Worker receipt confirmed/)).toBeVisible({ timeout: 45000 });
  await page.screenshot({ path: testInfo.outputPath('document-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('document-mobile.png'), fullPage: true });
  await page.getByRole('link', { name: 'Library', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill(title + ' duplicate');
  await page.getByLabel('Choose PDF files or drag them here').setInputFiles({ name: 'browser-fixture.pdf', mimeType: 'application/pdf', buffer });
  await page.getByRole('button', { name: 'Upload documents' }).click();
  await expect(page.getByRole('alert')).toContainText('Duplicate file');
  await expect(page.getByRole('link', { name: 'View existing document' })).toBeVisible();
  await page.getByRole('link', { name: 'Ask', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ask with evidence' })).toBeDisabled();
});
